vispy/app/backends/_ipynb_webgl.py

This fixes the WebGL backend which is currently broken with IPython 3.0.dev.
IPython 3.0 installs nbextensions in a system-wide directory by default. VisPy will install the nbextensions in a user directory to avoid permissions errors.
Ready for review/merge.

Add IPython version check in WebGL backend

---

vispy/app/backends/_qt.py

Opening this PR for discussion:
When a canvas is closed using the Qt backend, it should be possible to show the canvas again by calling `show()` on it. It should only be closed permanently if the user requests that or if the canvas is collected.

Removed closeEvent for qt backend

---

examples/ipynb/colormaps.ipynb
vispy/color/colormap.py

* Upgraded notebook to IPython 3.0
* Renamed `discrete` to `zero` in the notebook examples
* Fixed minor issue in colormap linear interpolation error message
Ready to merge.

Fixed colormap example notebooks

---

vispy/__init__.py

To 0.4.0-dev. The current indicated version (0.3.0) is wrong...
Closes #688.

Bump VisPy version

---

vispy/geometry/__init__.py
vispy/geometry/generation.py

Two minor fixes for vispy.geometry:
1) Changed create_cylinder and create_cone to explicitly set the face array datatype to np.uint32, matching the behavior of create_sphere (N.B. np.uint defaults to np.uint64 on some systems, which breaks these functions)
2) Expose the create_arrow as an external method of the geometry module, matching the behavior of the other .create_ methods.

Minor fixes for vispy.geometry

---

vispy/geometry/__init__.py
vispy/geometry/generation.py
vispy/geometry/meshdata.py
vispy/geometry/polygon.py
vispy/geometry/triangulation.py

I ran into another issue with vispy.geometry on 64-bit python (specifically when creating a MeshData from unindexed vertices), so I went ahead and made all the implicit-width datatypes 32-bit (haven't run into any issues yet).
I also exposed the create_cone function, so all the .generation.create_ methods are now exposed in vispy.geometry with similar default parameters.

More minor vispy.geometry fixes

---

doc/ext/gloooverviewgenerator.py
vispy/gloo/__init__.py
vispy/gloo/glir.py
vispy/gloo/program.py
vispy/gloo/tests/test_program.py
vispy/gloo/tests/test_texture.py
vispy/gloo/texture.py

So, I implemented a 1d sampler similar to the already existing 3d sampler in the codebase by accessing ```pyopengl```. There a lot of layers and moving parts, so I'm not sure if I missed something in my implementation.
I also had to manually extract the constants ```GL_TEXTURE_1D``` and ```GL_SAMPLER_1D```. I'm assuming that they were not listed in ```_constants.py``` since they're not ```GLES2.0```? Either way, I'm not too fond of the current __extremely__ hacky solution I came up with. Would love a nicer solution

Implement a 1d sampler using pyopengl

---

vispy/app/backends/_qt.py
vispy/app/canvas.py
vispy/util/event.py
vispy/util/logs.py

Closes #560.
Test code:
```
from vispy.app import Canvas
class MyCanvas(Canvas):
def on_draw(self, event):
raise RuntimeError
x = MyCanvas(show=True)
```
Changes this output (`master`):
```
WARNING: Error invoking callback <bound method MyCanvas.on_draw of <Vispy canvas (PyQt4 (qt) backend) at 0x32dd940>> for event: <DrawEvent blocked=False handled=False native=None region=None source=<Vispy canvas (PyQt4 (qt) backend) at 0x32dd940> sources=[<Vispy canvas (PyQt4 (qt) backend) at 0x32dd940>] type=draw>
WARNING: Error invoking callback <bound method MyCanvas.on_draw of <Vispy canvas (PyQt4 (qt) backend) at 0x32dd940>> repeat 2
```
Into this:
```
RuntimeError
ERROR: Invoking <bound method MyCanvas.on_draw of <Canvas (PyQt4) at 0x237abe0>> for DrawEvent
ERROR: Invoking <bound method …
```

FIX: Shorter rep

---

vispy/app/backends/_glfw.py

(This pull request is not ready to merge yet, but is intended to continue the discussion of #551 specifically for the GLFW use-case and fixing the tests.)
Currently with GLFW, the tests fail on Retina displays:
````
======================================================================
FAIL: Test drawing to a framebuffer
----------------------------------------------------------------------
Traceback (most recent call last):
File "vispy/gloo/tests/test_use_gloo.py", line 43, in test_use_framebuffer
assert_equal(c.size, shape[::-1])
nose.proxy.AssertionError: Tuples differ: (600, 200) != (300, 100)
First differing element 0:
600
300
- (600, 200)
?  ^    ^
+ (300, 100)
?  ^    ^
````
Based on @lcampagn's comment: assuming `canvas.size` should return the window size, I tried changing the …

Fixing GLFW Tests & Support for Retina Devices

---

examples/basics/visuals/cube.py
examples/basics/visuals/image_transforms.py
examples/basics/visuals/image_visual.py
examples/basics/visuals/line.py
examples/basics/visuals/line_plot.py
examples/basics/visuals/line_transform.py
examples/demo/gloo/imshow.py
examples/demo/gloo/imshow_cuts.py

`self.show(True)` or `app.Canvas.__init__(self, show=True)` should
only be called after the rest of the initialisation code has run.

Fixed a few examples on OS X

---

vispy/app/backends/_wx.py

Wx converts the second mouse-press into a Click event.
This change converts these DClick events into standard vispy_mouse_press events, so that mouse press events are not skipped

Convert wx DClick into vipsy_mouse_press events

---

vispy/scene/canvas.py

This makes it easier to dynamically change the bgcolor.
Changing one line to two lines in the `__init__` isn't so nice...it could be left as it was and work fine but with very minor code redundancy.

Proposing a bgcolor property for SceneCanvas

---

vispy/gloo/context.py
vispy/gloo/tests/test_context.py
vispy/gloo/wrappers.py

issues: closes #757
Better error message, and a class to help use gloo without an `app.Canvas`.

Allow using gloo without vispy.app again

---

vispy/visuals/line_plot.py

fixing [feature request](https://github.com/vispy/vispy/issues/718)
Allow ```LinePlotVisual.set_data``` without having to specify the position

allow LinePlotVisual.set_data(..) to only recieve keywords

---

vispy/visuals/tube.py

Previously the tube tangents were calculated assuming the tube was closed, which messed up the first and last tangent values unless they happened to match anyway. The problem is shown in the images below. I also rearranged the doc (and added a missing parameter) to emphasise the main arguments.
Example tubes before this PR:
And after:

Fixed a TubeVisual bug and rearranged doc

---

setup.py

This adds some Extra requirements, so that one can do something like `pip install vispy[ipython-vnc]` (or some other backend) and the additional dependencies would be installed.
Unfortunately, it seems like PyQt4/5 don't install eggs and don't have proper information on PyPI, so I wasn't able to add the correct dependencies there. I also added some minimum requirements when I could find checks for them, but couldn't see anything describing requirements for all backends.

Optional install requirements

---

vispy/gloo/glir.py

@rossant happier now? :) This changes the "unset variables" and "not an active uniform/attribute" to be INFO instead of WARNING level. Note that I did *not* change the "invalid command" warnings to info, since those seem like they really shouldn't occur and would be indicative of deeper problems.

FIX: Use info for unset vars

---

examples/benchmark/scene_test_1.py
examples/benchmark/scene_test_2.py
vispy/scene/canvas.py
vispy/scene/systems.py
vispy/util/config.py
vispy/util/profiler.py
vispy/visuals/line/line.py

Adds a Profiler class and instruments some visual/scenegraph code. Should add negligible overhead when profiling is not in use. Works like this:
```
python example.py --vispy-profile=SceneCanvas.draw_visual
python example.py --vispy-profile=all
```

Scenegraph profiling

---

vispy/geometry/generation.py

Currently the cube mesh generation function returns a 1D array of face indices, but the MeshData expects it to be 2D. This doesn't seem to affect anything right now as functions like `cube._meshdata.get_vertex_normals()` are not accessed, but exceptions are raised if that code is actually called. This PR just fixes that, everything seems to work fine afterwards.

Fixed Cube mesh generation

---

vispy/util/fetching.py

Each commit explicitly references the test-data commit ID it should be tested against.
This should allow #870 to be merged without breaking other branches.

Explicit commit ID for image testing

---

examples/basics/scene/volume.py
vispy/color/__init__.py
vispy/color/colormap.py
vispy/gloo/preprocessor.py
vispy/gloo/texture.py
vispy/gloo/wrappers.py
vispy/scene/cameras/cameras.py
vispy/scene/node.py
vispy/scene/systems.py
vispy/scene/visuals.py
vispy/scene/widgets/viewbox.py
vispy/visuals/gridlines.py
vispy/visuals/image.py
vispy/visuals/mesh.py
vispy/visuals/polygon.py
vispy/visuals/volume.py

The main purpose of this PR is to add a couple of new volume rendering methods, but many ancillary changes are included.
* Add "translucent" rendering method (better quality compositing but requires more effort in selecting colormaps)
* Add "additive" rendering method (nice for visualizing 3D functions like electron orbitals)
* Reorganized a "bit" of the volume fragment shader core--improved performance, simpler code, somewhat easier to understand.
* Tweaked isosurface rendering; no more ray randomization.
* Added Z-interpolation to emulated 3D texture
* Disabled comment removal from shader preprocessing (@rougier, was this necessary?)
* Fixed `VisualNode` double-init bug (see #871) 
@almarklein, please be critical--I imagine I have not tested the volume rendering under all of the cases …

Volume rendering methods

---

examples/demo/gloo/imshow_cuts.py

On window managers where the requested window size is not always respected (I'm on AwesomeWM but I assume other tiling WMs like XMonad etc do the same thing), the tests will fail since they assume the window has not been resized. We should be resilient to this.

Fixed out-of-bounds mouse errors on example resize

---

vispy/scene/widgets/widget.py

A debug print statement was left from a previous PR:
```
(colour-analysis)Kali-2:bin kelsolaar$ ./analysis 
8
10
8
10
8
10
0
0
0
0
0
10
10
10
10
10
10
0
0
10
10
10
10
```

Remove debug print statement.

---

README.rst

Current badges are a bit inconsistent. Switching to the SVG versions makes them all the same height and shading.

Switch to SVG version of badges.

---

vispy/app/backends/_ipynb_webgl.py
vispy/gloo/context.py
vispy/gloo/gl/gl2.py
vispy/gloo/gl/tests/test_basics.py
vispy/gloo/glir.py
vispy/gloo/tests/test_context.py
vispy/gloo/tests/test_glir.py
vispy/testing/_runners.py

Closes #669.
This does the following:
1. gets us some information available at the GLIR consumer level for desktop
2. gives the GL version number when GL errors are thrown (e.g., no `glBindFramebuffer` when users have version < 3.0)
Now we can at least query some things like:
```
canvas.context.shared.parser.capabilities['max_texture_size']
```
It's a bit nested, but I'm not sure the best way to un-nest it. Should be a decent start.

FIX: Add some information about GLIR consumer

---

examples/basics/visuals/line_draw.py

Hi, 
I'm looking into a simple vector graphics sketching framework, possibly as an add-on to vispy. As a first test I extended the line plot visual to add mouse events and simple mouse editing. The demo is based on various line-plot and pan-zoom demos from existing examples. In principle the demo works with multiple lines, but as a click into empty space creates a new point for all lines in this demo, it is somewhat unintuitive. 
It seems to me that other visuals could be extended in a similar way, maybe even with a generic wrapper for basic point editing. Comments are welcome how to best integrate or add this feature.
A potential issue I discovered is that the left-click pan interferes with left-click dragging line points. It would be great if the mouse buttons for camera actions could …

Added example for mouse editing of line plot

---

setup.py

So, I just realized I made a silly typo here. Although why `setuptools` developers decided to make everything plural _except_ this one option, I don't know...

Fix typo in setup requirements.

---

vispy/gloo/glir.py
vispy/gloo/globject.py
vispy/gloo/tests/test_glir.py

Ready for review/merge.
This resolves a performance issue where scenes with a large number of visuals were visiting `GlirQueue.clear()` thousands of times per draw.

Different method of associating glir queues (for better performance)

---

.gitignore
examples/basics/visuals/box.py
examples/basics/visuals/plane.py
vispy/geometry/__init__.py
vispy/geometry/generation.py
vispy/geometry/tests/test_generation.py
vispy/visuals/__init__.py
vispy/visuals/box.py
vispy/visuals/plane.py

This PR implements support for a parametric plane and a parametric box that builds on it through the following objects:
- `vispy.geometry.generation.create_plane`
- `vispy.geometry.generation.create_box`
Some things to consider:
- It would be neat to actually return a `MeshData` instance instead of the current tuple for `create_cube`, `create_plane` and `create_box` definitions, however the class may not have all the needed fields, especially one for the outline. Upon really quick inspection it doesn't seem to support arbitrary data.
- As I didn't wanted to break anything, I did not replaced `make_cube`, it is maybe worth for it to be an alias to `make_box` or whatever you feel the best.
- I haven't created matching visuals for the new geometries, but I have some that fit my usage …

PR: Support for parametric plane and box geometries.

---

vispy/gloo/gl/tests/test_functionality.py

The attribute `a_1` is assigned generic vertex attribute 0, which has some magical properties on legacy desktop GL. By reversing the order, it no longer has such assignment, and works like any other attribute. The new first attribute `a_4` is not modified in the same way as `a_1`, and thus does not suffer due to the magical properties of index 0.
I also fixed a minor typo.
Fixes #649. CC @rossant who was also seeing this issue.

Fix functionality tests on Intel and software GL.

---

vispy/ext/six.py

I've noticed a few new warnings due to the six shim that I didn't see earlier (because of Python 3.4 upgrade, probably).

Fix ResourceWarnings in six shim

---

vispy/util/svg/color.py

`itertools.combinations` != double loop comprehension. `combinations` excludes doubled entries, so values like '00' did not exist. This fixes the broken tiger example (are these not tested on Travis?).
Possibly the reason why it seemed in #932 that the explicit loop was twice as fast may be due to the fact that this code produces only 231 entries, when there should be 484.

FIX: Restore missing values in hex-to-decimal dict.

---

LICENSE.txt

Maybe a test should be added asserting that the listings of core contributors all match each other.

Include Eric Larson

---

vispy/app/backends/_qt.py
vispy/app/qt.py

A small bug fix in Qt backend.
In pyqt5 `QtCore.qInstallMessageHandler` takes a function with a different signature than pyqt4. The result was that all pyqt5 log message would display `TypeError: message_handler() takes 2 positional arguments but 3 were given`.
This PR fix the issue by checking wether `qt_lib` is pyqt4 or pyqt5.
PS: I also add a `.decode()` to pyqt4 logging message signature because it's return a byte and not an str. However it could raise issue with Python 2. This code has only been tested with Python 3.4.

Add new signature to `message_handler` for pyqt5

---

vispy/app/canvas.py

It must be a tuple to match other usage of dimensions.
For example, [here](../blob/master/vispy/scene/canvas.py#L266):
```python
prof('create SceneDrawEvent')
vp = (0, 0) + self.physical_size if viewport is None else viewport
scene_event.push_viewport(vp)
prof('push_viewport')
try:
```

Fix type of canvas size.

---

vispy/visuals/surface_plot.py

set_data later sets self.__colors (though nothing ever reads from either attribute), so I guess this is a small and currently irrelevant typo

Fixed SurfacePlotVisual attribute name

---

vispy/visuals/volume.py

The Volume docstring originally mentioned that the data should be 2-dimensional, which I presume was a typo?

Minor fix to Volume docstring

---

Makefile
make/make.py
vispy/testing/_runners.py

closes #993 
Also added an option to the makefile so you can write ```make docs```.
the syntax to invoke this test is ```python make.py test docs```.

add test docs option to make.py

---

setup.py

This is useful if someone is trying to use `python setup.py develop` but doesn't have `setuptools`.
There's a nested import (which loads `warnings.warn`). I will move that to the top level if it is  necessary, but I think the nested import is "neater" since it isolates usage

add a warning when setup.py is unable to load setuptools

---

LICENSE.txt

Core distinction is unnecessary, this gets rid of it for the license. Ready for review/merge. I'll tackle the website hopefully soon.

FIX: Remove core distinction

---

examples/demo/scene/oscilloscope.py

See #1025.
I'm still seeing a `RuntimeError: OpenGL got errors (glTexImage2D): GL_INVALID_VALUE` though.

Fix oscilloscope demo without pyaudio installed

---

setup.py

Some shaders were not copied during the installation process, which made some examples crash.

Fix installation

---

vispy/glsl/build-spatial-filters.py
vispy/glsl/misc/spatial-filters.frag

This PR fixes an offset issue within the spatial-filters fragment shader. See discussion in #1017.

FIX: add proper offset to spatial-filter fragment shader

---

examples/basics/gloo/spatial-filters.py
examples/basics/gloo/spatial_filters.py
vispy/io/__init__.py
vispy/io/datasets.py

PR suggested in #1017 and as follow up to #1048.
The added example shows the available 17 interpolations in spatial-filters.frag . Toggling with 'Left' and 'Right' arrow keys. The actual used filter is shown in the window title.

add spatial-filters example in examples/basic/gloo

---

examples/basics/scene/image.py
vispy/visuals/image.py

As discussed in #1017:
This is a first attempt to implement spatial filtering to image visual.
The example works, but the handling with the "hardware" modes ('nearest', 'linear') is still broken. 
For every interpolation a dedicated lookup_function is created and fit to the shader_program as needed. I'm open for any suggestions to improve this. I already thought about subclassing ImageVisual, but that should not be mandatory.
There is sure a lot of room for improvement.

WIP: add interpolation to ImageVisual and respective example

---

vispy/util/svg/geometry.py

Puts in the modified BSD license for AGG 2.4 derivative.
Closes #1065.
Ready for review/merge @rougier.

FIX: Fix license

---

vispy/visuals/text/text.py

This is a follow up to #1069.
TextVisual uses now the reworked filtering with float packed rgba interpolation kernel. 
* Examples are working
* Test is passing (it doesn't test this part because of font_size)

make TextVisual use spatial-filter.frag with packed kernel

---

vispy/app/backends/ipython/_widget.py

Jupyter/IPython 4 uses a slightly different API for the callback.
Fixes #1081

Fix VispyWidget callback args for jupyter

---

vispy/visuals/filters/picking.py
vispy/visuals/mesh.py

Without these fixes, the shaders don't work on Android, so I think (but am not certain) it's an ES2 compatibility thing.

Made some shaders work with ES2

---

vispy/app/backends/_qt.py

This is a fix for  #1063.
In resizeGL Qt reports only the physical size of the framebuffer. To mirror the behaviour of the GLFW backend, the physical_size is now stored and can be accessed when the resize event fires, so tha the correct physical size of the frame buffer is set on HiDPI displays. Only tested with PyQt5 on Mac.

Added physical_size to Qt backend to manage different fb size on Retina displays

---

examples/demo/scene/flow_lines.py

When calculating the row and column indices, there was a division by shape.y instead of shape.x, causing bugs when using a non-square vector field.

Fixed a bug when using rectangular vector field

---

vispy/color/colormap.py
vispy/ext/cubehelix.py

While co-working with VisPy and matplotlib I wondered why the VisPy cubehelix implementation misses the green parts of the colormap. First I thought this is with the standard cubehelix implementation and tried to change `start`, `rot` and other keywords. Nothing happened, this was due to `cubehelix` was already instantiated within `colormap`-module and no pure class any more. 
The colors were not influenced by this change, so I found that **rgb** was in the wrong order **rbg**. After changing this everything works as expected (as far I can see).

FIX: cubehelix issues

---

vispy/gloo/gl/_gl2.py

Quickfix to add allow glReadPixels using GL_DEPTH_COMPONENT to read the depth buffer on desktop GL.

Allow GL_DEPTH_COMPONENT in glReadPixels

---

vispy/visuals/volume.py

Sometimes the loop does not assign a value to gl_FragColor, and on some GPUs it produces rather unpleasant results.
Fixes #966.

Initialize gl_FragColor in iso volume renderer.

---

vispy/scene/cameras/base_camera.py

This calls `camera.view_changed` when `camera.depth_value` is set. Otherwise, one has to wait for the next view refresh to see the result.

Call view_changed when camera.depth_value is set

---

examples/basics/scene/save_animation.py

Adding a save_animation example in examples/basics/scene/. Uses imageio to save a few rendered frames from the sphere example in a gif

adding save_animation example

---

vispy/scene/widgets/widget.py

I'm not sure if there are other problems related to this (like setting the parent in the first place - but other places do reference self.parent so maybe that's expected), but the method doesn't exist so this at least prevents an actual crash.

Removed call to non-existent Widget.remove_parent

---

vispy/scene/widgets/widget.py

Following my previous PR at https://github.com/vispy/vispy/pull/1132, I now think that it's very important to set the parent of a widget to None when it's removed. If this isn't done, it's removed from the widget tree but not from the Node heirarchy (where parent is actually used), and so is actually still displayed on screen but in a funny buggy way.
I'm not certain what is the intended way for this to work, but I'm fairly confident this fix is an unambiguous improvement; with it, removing widgets seems to work as expected, and I haven't found any further problems.
The improperly-removed Nodes also seem to have been the reason for the mouse input problems I mentioned on gitter.

Unset widget parent when removed

---

vispy/ext/_bundled/png.py
vispy/ext/_bundled/six.py
vispy/ext/six.py

Six 1.8.0 appears to be the latest version available on Debian stable. Ubuntu and Fedora are both on 1.9.0. I changed the shim to use `importlib` where available (2.7+) which should allow vispy to be frozen.
@jdreaver Can you see if this works? Right now, it seems like you need to freeze `six` as well, even though the bundled copy is there. I haven't figured out why it can't see it, but I think this is a good enough work-around for the time being.
Fixes #1074 hopefully.

Update bundled six to 1.8.0 and allow it to be frozen

---

vispy/geometry/calculations.py

By some .obj files (for example obj files generated with FreeCAD) the read_mesh function fails because of a numpy bug (in numpy repository under bug 823, 4366 and 4384). 
Because handling the numpy bug would be too complex, I corrected the code here.
By using this modification I was able to read all obj files.

bugfix vispy.io.read_mesh fails because of numpy bug #823

---

vispy/visuals/collections/agg_path_collection.py

I had troubles running examples `collections\tiger.py`and `collections\chloropleth.py` because of a small problem with type casting in newer versions of numpy.
So I hope this tiny fix is helpful.

BUG: Type casting error in agg_path_collection.py

---

vispy/testing/image_tester.py

This is just a documentation thing - so others won't need to run a `git grep` to find out where the config file lived

added info about where config file is located

---

vispy/scene/widgets/axis.py

When instantiating AxisWidget class with *orientation='right'* or *orientation='top'*, the function AxisWidget.on_resize raises an exception because AxisWidget._axis_ends supports only 'left' and 'button' orientations.
This PR adds support for 'right' and 'top' orientations in function _axis_ends of AxisWidget class.

top and right orientations in AxisWidget

---

vispy/geometry/isosurface.py

The ``vispy.geometry.isosurface.isosurface(...)`` function makes use of the ``strides`` property of arrays, and we therefore need to make sure that the data is contiguous.

Fix isosurface function for non-contiguous arrays

---

vispy/visuals/isosurface.py
vispy/visuals/tests/test_isosurface.py

In master, if one creates an ``IsosurfaceVisual``, the ``color`` property which is normally settable for ``MeshVisual`` is not settable for ``IsosurfaceVisual`` because ``set_data`` doesn't accept colors:
```
In [2]: surface.color = (1, 0.5, 0.3, 1.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-c4c805007590> in <module>()
----> 1 surface.color = (1, 0.5, 0.3, 1.0)
/Users/tom/tmp/vispy/vispy/util/frozen.py in __setattr__(self, key, value)
15                                  '"unfreeze()" to allow addition of new '
16                                  'attributes' % (key, self))
---> 17         object.__setattr__(self, key, value)
18 
19     def freeze(self): …
```

Fix bug that caused settable Isosurface.color property to not work

---

vispy/gloo/tests/test_program.py

Fix Typo in the Name of a gloo Program Test

---

vispy/gloo/context.py

Several problems have been reported when using 16 bits depth (see #1174, #1175, #896).
This PR sets default to 24.

Set default depth to 24 bits 

---

vispy/visuals/isosurface.py

Fix a error that the color parameter in `isosurface` can not be set.
#1176

fix isosurface error : color can not be set

---

examples/basics/visuals/line_plot3d.py
vispy/visuals/line_plot.py
vispy/visuals/markers.py

#1189 
In `gloo.visuals`, both `LineVisual` and `MarkersVisual` have 3D capability, but in `LinePlotVisual`, 3D is disabled, which makes some typical visual task such as `plot3d`, `scatter3d` not available. This patch enables this feature, and provides a simple demo on using `LinePlotVisual` as a `plot3d` or `scatter3d` command in `examples/basic/visuals`.

enable 3D plot in LinePlotVisual, add a demo using plot3d

---

README.rst

Make Qt point to http://www.qt.io, as new python developers may not be aware of it.

doc: Add URL link for Qt in README.rst

---

vispy/visuals/mesh.py
vispy/visuals/tests/test_mesh.py

This is because previously, set_data would get called with just the color, but this resulted in MeshData being reinitialized with all parameters set to None.

BUG: fixed a bug that caused a mesh to disappear if the color was set using the .color attribute

---

examples/basics/scene/volume.py

Add an extra axis view in the left top to show the rotation of the volume visual. The location and scale of this axis is relative to the `Viewbox` coordinates in the GUI rather than the internal scene. Now only available for the `TurntableCamera`.

Update volume.py with an top left axis view

---

vispy/geometry/isosurface.py

Before this, j was a one-element array and Numpy raised the error:
```
TypeError: only integer scalar arrays can be converted to a scalar index
```

Fix isosurface function for use with Numpy 1.12.0.dev

---

vispy/visuals/line/line.py

I believe this is a trivial sync of the documentation with the implementation.  
If it's not, then the code should probably be fixed up by someone more familiar with subtleties of how rendering is supposed to work in vispy.

Fix line width related documentation error

---

.travis.yml

I think continuum recently added PyQt5 to conda and called it pyqt with version 5, so we need to pin the version to 4.

Fix Travis failures by pinning Qt/PyQt versions

---

appveyor.yml

Currently, the Qt tests are being skipped on AppVeyor, I think because PyQt5 is getting installed

Pin PyQt to PyQt4

---

.travis.yml

Currently, one of the builds is failing because it is using PyQt5

Travis: make sure PyQt stays pinned to PyQt4

---

vispy/html/static/js/webgl-backend.js

The location of the widgets has changed in current versions of ipython/jupyter. Credit goes to @SamiAhola who posted this fix several months ago on the gitter vispy channel. However no PR for the fix has been made so I have made one here.

webgl backend fix for updated versions of ipython/jupyter notebook

---

vispy/scene/widgets/grid.py

This PR makes the grid widget much more usable by not forcing the solver to re-solve if the overall width and height of the plots haven't changed.  This makes all the examples that use the grid widget extremely responsive compared to not using this pull request.
I couldn't find any case that was worse than without the patch, and I tested all the examples in `examples/basics/plotting` and `examples/basics/scene`.
This PR does not improve the situation whenever the entire canvas is resized, but it is no worse than without the PR.  It may improve issue #1182 as well.

Only resolve grid layout using Cassowary if required

---

vispy/gloo/texture.py

This fixes an issue that I've seen Windows Python 2.7 users come across. Numpy appears to return long integers when accessing array shapes, which causes issues in places such as this.

Cast values to native ints to avoid issues on Windows with Python 2.7

---

examples/demo/scene/oscilloscope.py

Fixes an error in the oscilloscope demo that was introduced by a recent numpy API change:
```
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
```

Correction in oscilloscope demo to handle numpy API change

---

vispy/gloo/program.py

The 4th argument of `re.sub()` is maximum number of substitutions, not flags.
Moreover, `re.M` affects only semantics of `^` and `$`, so it wouldn't have any effect on this regular expression.
Found using [pydiatra](https://github.com/jwilk/pydiatra).

Remove misplaced flags from re.sub() call

---

vispy/color/colormap.py

Changed number of samples from 128 to 64 in creation of the viridis color map (changed sample stride from 2 to 4). Note the original viridis colormap is defined by 256 samples.
This allows a good (barely visible artifacts) interpolated approximation to the original viridis colormap with at most <1% error as elaborated in #1331. Without this change less GPUs are able to use the viridis colormap along with the ColorBar. This change expands the number of GPUs that are compatible.

viridis colormap change from 128 to 64 samples

---

vispy/gloo/framebuffer.py
vispy/gloo/tests/test_framebuffer.py

The original behavior was to assume a color texture. This fetches the
format using the format ID which allows the use of other framebuffer
texture e.g. depth.

Properly infer framebuffer format.

---

examples/basics/visuals/mesh.py
vispy/color/colormap.py
vispy/geometry/meshdata.py
vispy/gloo/buffer.py
vispy/visuals/image.py
vispy/visuals/mesh.py
vispy/visuals/visual.py

Allows doing a vertex value->colormap mapping with meshes.

MRG: Better mesh options

---

.travis.yml
examples/basics/gloo/spatial_filters.py
examples/basics/visuals/line_transform.py
vispy/app/backends/_wx.py
vispy/testing/_runners.py

Mac OSX complains about the program having unset variables.
```
Example basics/gloo/spatial_filters.py failed (0):
----------------------------------------------------------------------
INFO: Program has unset variables: {'u_shape'}
```

Fix spatial_filters example on mac

---

.travis.yml
vispy/app/backends/_wx.py
vispy/gloo/gl/tests/test_functionality.py

Certain tests fail when a backend is used on OSX (see #1178). Currently Travis includes an OSX standard set of tests but without using any backends. This PR adds a test environment for unit testing backends. Currently this is just PyQt4, but should include wxPython once it is available for OSX on conda-forge (currently takes to long to build on CI).
This PR includes removing OSX as an environment that is allowed to fail. I'm assuming that `test_functionality.py` will fail also which will require some special handling (again see #1178).

Add OSX standard/unit tests to travis

---

vispy/geometry/generation.py
vispy/visuals/sphere.py

Fix #1259 
Based on the above issue it seemed a little weird that no one would have noticed two parameters being backwards. What was actually wrong was that the code for the `cube` method was wrong twice so the issue wasn't showing. The `latitude` method was actually the method that showed the issue. If @kalexander92 and maybe @kmuehlbauer or @larsoner could test `examples/basics/scene/sphere.py` with this branch and try changing the rows and cols of the third sphere and see if the numbers make sense to them.

Fix sphere passing rows/cols backwards

---

vispy/glsl/arrowheads/arrowheads.frag
vispy/glsl/arrowheads/arrowheads.vert
vispy/visuals/line/arrow.py
vispy/visuals/line/line.py

This is related to : #1376 
```python
"""XYZ axis example
"""
from vispy import scene, app
from vispy.scene.visuals import Arrow
can = scene.SceneCanvas(show=True)
wc = can.central_widget.add_view()
wc.camera = 'turntable'
wc.camera.center = (0., 0., 0.)
wc.camera.scale_factor = 3.
pos = np.array([[0., 0., 0.], [1., 0., 0.],
[0., 0., 0.], [0., 1., 0.],
[0., 0., 0.], [0., 0., 1.],
])
arrows = np.c_[pos[0::2], pos[1::2]]
line_color = ['red', 'red', 'green', 'green', 'blue', 'blue']
arrow_color = ['red', 'green', 'blue']
arr = Arrow(pos=pos, parent=wc.scene, connect='segments',
arrows=arrows, arrow_type='triangle_60', arrow_size=20.,
width=3., antialias=True, arrow_color=arrow_color,
color=line_color)
can.show()
app.run()
```

Enable the definition of arrows along z-direction

---

MANIFEST.in
setup.py

Fix #1382 
The 2nd commit in this PR will need to be cherry picked in to a maintenance branch so that the 0.5.0 package can be repackaged and upload to PyPI. We may need to make a new build revision for conda-forge (@kmuehlbauer FYI) so this gets rebuilt too.

Fix doc directory in source tarball

---

MANIFEST.in
vispy/scene/widgets/grid.py

Fix #1385 
Includes adding LICENSE.txt to MANIFEST.in for source tarball distributions.
Using the test script below I found out where I think the axes limits are being messed up in the initial drawing of the plot.
```
import vispy.plot as vp
from vispy import app
x = np.linspace(0, 1000, 1000)
y = np.linspace(0, 50000, 1000)
line = None
fig = None
fig = vp.Fig(size=(1200, 380), position=(-40, -50))
fig.create_native()
x = np.linspace(0, 1000, 1000)
y = np.linspace(0, 50000, 1000)
line = fig[0, 0].plot((x, y), width=1, color='blue', xlabel='',
ylabel='', marker_size=-10)
app.run()  
```
Note that the above script differs from the one in #1385 by using the default `'gl'` line instead of `'agg'`. The 'agg' line method does not clip lines outside of the drawing axes box. …

Fix initial axis limits in PlotWidget

---

vispy/testing/image_tester.py
vispy/visuals/ellipse.py
vispy/visuals/polygon.py
vispy/visuals/rectangle.py
vispy/visuals/tests/test_rectangle.py

Fix #1349
Issues fixed:
- Border width was not used in RectangleVisual
- Border loops were not properly being closed due to a 1 versus -1 index error.
This refactor tries to reduce the amount of duplicated code. There is something weird going on in the original code where the center point of the polygon's face (ellipse and rectangle) was being passed as a mesh vertex but as far as I can tell it is not needed.
Lastly, updating the rectangle/ellipse vertices could be done differently but I would argue no less ugly (`_regen_pos()`).

Refactor ellipse and rectangle visuals

---

examples/basics/scene/one_scene_four_cams.py

closes #1124
Multiple Views are currently not implemented. I cleaned up the example which used to show multi-parenting and left a note to #1124.

MIN: clean up examples/basics/scene/one_scene_four_cams.py

---

examples/basics/scene/isocurve.py
examples/basics/scene/isocurve_updates.py
vispy/visuals/isocurve.py

* correct rows/cols in IsocurveVisualfor matplotlib isoline tracer
* fix examples to have (200, 100) dimension
closes #1403

FIX: correct rows/cols in IsocurveVisual 

---

vispy/visuals/markers.py

This PR add a if test to the vertex shader of markers.py to avoid drawing markers that have a 0. size

Don't draw zero-size markers

---

examples/demo/gloo/cloud.py

The cloud.py demo can render a few different shapes. The functions are using the global variable gl_PointCoord and ignoring the gl_PointCoord that is passed into the function. This does not affect behavior.

use passed in variable P instead of gl_PointCoord in demo/cloud.py

---

examples/basics/gloo/animate_shape.py
examples/basics/gloo/display_lines.py
examples/basics/gloo/display_points.py
examples/basics/gloo/display_shape.py
examples/basics/gloo/hello_fbo.py
examples/basics/gloo/multi_texture.py
examples/basics/gloo/start.py
examples/basics/plotting/scatter_histogram.py
examples/demo/gloo/boids.py
examples/demo/gloo/cloud.py

The extra space makes the shebang not work, e.g.:
```shell
vispy/examples/demo/gloo$ ./cloud.py 
./cloud.py: line 7: $'\nDemonstrating a cloud of points.\n': command not found
```

Remove extra space between # and ! in shebangs.

---

.travis.yml
vispy/testing/__init__.py
vispy/testing/_testing.py
vispy/visuals/isocurve.py

Fixes #1437 
I separated out the commits so if we want to temporarily support both MPL and skimage we can go back to the previous commit.

Fix IsocurveVisual to use scikit-image instead of matplotlib

---

vispy/app/backends/_qt.py

Fixes #1440 
As pointed out in the related issue this shows up when a canvas is created with `fullscreen=True` and `show=True` for the PyQt4 or PyQt5 backend on HiDPI displays. Originally I thought this was only PyQt5.
The issue was that the call to make the widget/canvas visible ran `self.showFullScreen()` if `fullscreen` was True, but after this the physical size of the widget was set using the original canvas size. By moving the physical canvas size assignment before the visible/show call this should fix all of these cases. I've tested this with PyQt4 and PyQt5 examples on my OSX HiDPI display.
@kmuehlbauer Could you try out a simple example on your non-HiDPI display? @mkkb If you test out this branch, does it work for you?

Fix Qt windows that were created with fullscreen=True on HiDPI displays

---

vispy/gloo/framebuffer.py
vispy/scene/canvas.py
vispy/scene/widgets/grid.py
vispy/scene/widgets/widget.py
vispy/visuals/transforms/transform_system.py

I have been playing with the performance of vispy a bit #628 - my main test is examples/benchmark/scene_test_2.py. I'm not sure about everyone else who runs the benchmark but I found it impossible to use the scene canvas with a pyglet backend.
If I understood things in the code correctly, one major performance bottleneck is the generation of many upon many of update calls to the scene canvas, which simply schedule future draw events to be executed from the backend. It seems the major source of these are the scene nodes, all of which look to inherit and hold a reference to the scene canvas, and if a node update it triggered, it also calls the update on the canvas.
This pull might be an easy fix/work-around or at the minimum highlight a possible cause of poor performance in the scene and a …

WIP: Performance updates for Scene

---

vispy/util/event.py

Fixes the "nasty" bug described in #1033, which was caused by an event callback changing the list of callbacks.

Make events only propagate to callbacks that were present when the event was emitted

---

README.rst

The link to notebook currently links to a page that says the notebook has been relocated. This change changes the link to the end point.

Correct relocated link

---

vispy/visuals/markers.py

Fix memory leak in LinePlot (#1407) when no markers are to be rendered.

FIX: Memory leak in LinePlot.set_data (#1407)

---

vispy/color/colormap.py

Note that in [line.py](https://github.com/vispy/vispy/blob/master/vispy/visuals/line/line.py#L231) there's a `try/except` which is used to switch between colormaps and unique color. So I add a `KeyError` inside the `MatplotlibColormap` class but there's probably a better way to handle `KeyError`.
Small script to test it :
```python
from vispy import app
from vispy.scene.cameras import PanZoomCamera
cam = PanZoomCamera(rect=(0, 0, 20, 10))
sc = scene.SceneCanvas(bgcolor='black', show=True)
wc = sc.central_widget.add_view(camera=cam)
data = np.arange(200).reshape(10, 20).astype(float)
im_red = scene.visuals.Image(data, parent=wc.scene, cmap='tab20b')
app.run()
```

Use matplotlib colormaps (if installed)

---

vispy/scene/visuals.py

Fixes a bug in `VisualNode`'s `_update_opacity` function wherein opacity was being updated by setting a `ColorFilter`'s `color` property when the correct property to set was `filter`. Additionally calls the visual's `update` method upon filter change.
Since opacity only affects the `alpha` channel, additionally opts to replace the overly explicit `ColorFilter` with an `Alpha` filter. This prevents tampering with the RGB channels in the private filter.

BUGFIX: Properly update opacity in `VisualNode`s

---

examples/basics/visuals/text_visual.py
setup.cfg
vispy/glsl/build-spatial-filters.py
vispy/testing/_runners.py

This PR fixes flake errors that have been causing travis to fail. As part of this I moved the exclusions and ignored rules to setup.cfg so they are a little less hidden (or at least I think so). I also added W504 to the list of ignored rules which I think is a default ignore in the recent versions of flake8.
This PR also changes a `raise NotImplemented` to a `raise NotImplementedError` to satisfy flake8.
@mkkb There are still errors in `text_visual.py` that you semi-recently made changes to. The main issues are a `\e` and a `\?`. Any idea if those are necessary?

Fix flake errors

---

examples/demo/gloo/offscreen.py

In the example/demo/gloo/offscreen.py example, if we change the size to (1200, 600), e.g. the width is not equal to the height, we will get:
Where the right half of the image is empty.
I think it is a bug related to the size argument.
In this pull request, I change the order of width/height for Framebuffer and Texture2D, and get the result looks like:
I'm not sure it is the best solution.

fix size bug for offscreen.py example

---

appveyor.yml

Windows builds have started failing recently. Let's see if we can fix them.

Add CONDA_CHANNELS environment variable to appveyor

---

vispy/app/backends/_qt.py

This is similar to https://github.com/matplotlib/matplotlib/issues/8061 for matplotlib. I work on a macbook with a HiDPI retina display. My external monitor at work is not HiDPI. If I open a PyQt5 canvas on one monitor and drag it to another it gets in to a bad state. This is caused by the two displays having different device pixel ratios. This is the ratio of logical pixels to physical screen pixels. On HiDPI displays this is usually 2 and for regular displays it is 1.
PyQt5 allows you to know this ratio (`self.devicePixelRatio()`) and vispy already uses it to adjust physical versus logic pixel calculations. However, vispy only does this when first creating the window and on resize events. This means that if you get in to the bad state mentioned above you can resize the window and …

Fix qt5 based backends when moving window from one monitor to another

---

vispy/gloo/buffer.py

Weak references were being kept around in the list of Buffer._views,
which was causing unbounded memory growth.

Fix memory leak in DataBuffer.

---

vispy/visuals/transforms/base_transform.py
vispy/visuals/transforms/chain.py

The list of callbacks gets iterated over very often, so it's important
to make sure there aren't useless entries laying around.  Plus the
memory can grow without bound without correcting this.

Fix memory leak caused by keeping weak references to callbacks around.

---

.travis.yml

So this adds the recent conda strict `channel_priority`. This means, that if a package is not available on conda-forge it will be fetched from defaults without touching other depending packages.

FIX: set `conda config --set channel_priority strict` in travis

---

vispy/app/backends/_pyside2.py

The indention of the line
QtTest.QTest.qWait = qWait
should be so that it is only executed when the qWait function
needs to be monkey-patched.

Fix PySide2 qWait monkey patching

---

README.rst
setup.py

In #1610 I fixed setup.py to match the [ipywidgets cookiecutter](https://github.com/jupyter-widgets/widget-cookiecutter) for a notebook/jlab extension. As part of this PR I had removed the `vispy/static/*.js` files which are the bundled output of the javascript build process. Given the rest of the traditional ipywidgets installation process this meant that `setup.py` was now **requiring** that the javascript files be built before installing the rest of vispy. Obviously for a package like vispy this can't be a requirement (a notebook is only one possible backend/use case for our users). This issue is discussed further in #1619 where some users may not have `npm` installed or may have an older version that is unable to build the extensions for whatever reason.
I saw two possible solutions …

Fix setup.py to install vispy even if javascript compilation fails

---

.travis.yml
setup.py

Adding `python_requires` to the `setup.py` tells PyPI what client versions can download certain packages. By releasing the next version (0.6) with this and supporting python 2.7, this *should* make it the last version that python 2.7 clients are able to download automatically. It should avoid 2.7 clients downloading versions that are no longer python 2.7 compatible in the future.
Also looks like SDL2 on conda-forge is now causing issues on travis.

Add 'python_requires' to setup.py

---

vispy/visuals/tests/test_text.py
vispy/visuals/text/text.py

For now, only a unique rotation can be set to `TextVisual`. This PR allows to set an individual rotation to each text element.
```python
from vispy import app
cam = scene.cameras.PanZoomCamera(rect=(-2, -1.5, 4, 3))
sc = scene.SceneCanvas(bgcolor='white')
wc = sc.central_widget.add_view(camera=cam)
n_s = 20
theta = np.linspace(0, 2 * np.pi, n_s, endpoint=False)
text = ['Text_%i' % i for i in range(n_s)]
xy = np.c_[np.cos(theta), np.sin(theta)]
text_v = scene.visuals.Text(text=text, pos=xy, parent=wc.scene,
rotation=np.rad2deg(theta[::-1]))
sc.show()
app.run()
```

Add element-wise rotation to TextVisual

---

.travis.yml

See https://github.com/conda-forge/sdl2-feedstock/issues/13

Remove forced sdl2 version in travis config

---

vispy/testing/_runners.py

@kmuehlbauer can you see if this fixes case (3) of #1571 for you? It looks like our problem was having some empty strings at the start of the string list. At least for me it made installing with mode (3) no longer search all directories.
Also cleans things up a bit (hopefully!) by using `pytest -m pytest` directly rather than `pytest.main`. And no need for explicit faulthandler because `pytest-faulthandler` is enabled by default if it's installed (which is better than us making this extra call).
Closes #1571.
Closes #1572.

MRG: Remove empty strings at start of list

---

vispy/scene/cameras/panzoom.py

When zooming with the PanZoomCamera, I get a ValueError: The truth value of an array with more than one element is ambiguous. Here is a fix that works when center is none using a line that was changed in commit a8ee4f45a56ff9509546cade6439cdda841b7a04.
I stumbled upon this by running vispy/examples/demo/scene/picking.py using python3.7.2 and numpy 1.16.2.

Fix ValueError exception from ambiguous truth value in PanZoomCamera

---

examples/demo/gloo/skybox.py
vispy/gloo/__init__.py
vispy/gloo/glir.py
vispy/gloo/program.py
vispy/gloo/texture.py

**What does this implement/fix?**
Port skybox example from Glumpy #818 
**Additional information**
1) I fixed the `offset` tuple in the `set_data()` method of the `GlirTextureCube` class in `vispy/gloo/glir.py` because I wasn't sure about what it exactly does.
2) I did not find any alternatives for `trackball` so I used another way to interact from:
`examples/demo/gloo/terrain.py`. Most likely there is a more practical way.
3) I stored the images on my machine and tested locally but I guess they can be uploaded in `vispy/demo-data`.
4) I am not sure about the location of `skybox.py`, I put it in `examples/demo/gloo` by default.
It is still a work in progress but here is a rendering:

[MRG] Add TextureCube object and port skybox example from glumpy

---

pyproject.toml
setup.py

Closes #1651 
This adds a `pyproject.toml` to match PEP 518 specification so that build dependencies can be handled outside of `setup.py`. I'm hoping that @os-gabe @larsoner @renefritze and @kmuehlbauer could review and maybe test this for me as it is. Mainly, I'm wondering if the numpy/py27 setting is "good enough" for now. We won't be supporting python 2.7 after this next release, but it should at least work (is PEP 518 supported for py27?).
I'd like to add to this later with some changes to how `numpy` is imported in `setup.py` since I don't *think* it is needed the way we have it.
Also, does anyone know if there is a way to optionally require `npm` so that the jupyter widget can be built/compiled?

Add pyproject.toml file for better build support

---

vispy/io/mesh.py

**What does this implement/fix?**
Fix #1594 by creating a file object before sending it to `load_stl`.
**Additional information**
I was able to reproduce the bug on my configuration.

Fix read_mesh of STL files

---

vispy/gloo/framebuffer.py
vispy/gloo/tests/test_wrappers.py
vispy/gloo/wrappers.py

Closes #1250 
This is a simple hack for fixing reading depth buffers. The problem as described in the related issue was that when you asked to read the depth buffer the underlying `read_pixels` function was still asking for an RGB/RGBA array, meaning the color was being read. This PR fixes that by passing a `mode` parameter which can be color/depth/stencil and will use the appropriate GL constant when calling `glReadPixels`.
Questions for the maintainers:
1. Is `mode` the best way to solve this?
2. Should the return value always be 3D even if it is (rows, columns, 1) for depth and stencil?
3. I also realized that `stencil` mode doesn't work with the `crop` logic in frame buffer's `read` because there is no `self.stencil_buffer` attribute. Not sure the best way to fix this.
TODO:

Fix reading depth buffers with read_pixels

---

vispy/glsl/lines/agg.vert

This is a partial fix of #588. See the issue for screenshots and further discussion.
In general, my understanding of the issue is that the if statement commented out by this PR in `agg.vert` is/was causing the vertex shader to be exited too early; short-circuiting the logic that feeds the fragment shader for angles and other parameters to determine proper AGG line color and look.
As mentioned in the related issue, there still seems to be a non-alpha related issue where certain line joins show up as brighter parts of the line. Those will have to be fixed in a later PR.

Fix AGG line artifacts from transparent colors

---

vispy/app/backends/_egl.py
vispy/ext/egl.py
vispy/gloo/glir.py

Hi,
Here's a few changes that re-enables the EGL backend and makes it usable for accelerated off-screen rendering. This makes my application, as well as vispy/examples/demo/gloo/offscreen.py able to utilize truly headless rendering using EGL, using both standard OpenGL and OpenGL ES. Only tested with recent NVIDIA drivers.

Enable EGL backend for headless rendering

---

vispy/visuals/line/arrow.py
vispy/visuals/line/line.py

See https://github.com/napari/napari/issues/404
Talked with @seberg in person and now understand what the deprecation warnings in the above issue are talking about. This PR should fix the warnings from popping up and retain the current behavior.

Fix numpy 1.17 deprecation warnings about dtype creation

---

vispy/color/colormap.py
vispy/testing/image_tester.py

The texture-based `_glsl_step` (https://github.com/vispy/vispy/pull/1457) results in reversed colormaps when viewing non-interpolated colormaps (e.g. `Colormap(..., interpolation='zero'`).
Flipping the comparison here assigns the correct LUT entry. (e.g., the first control point should return 1 here, not N.)

Fix _glsl_step reversing discrete colormaps

---

examples/demo/gloo/primitive_mesh_viewer_qt.py
examples/demo/visuals/wiggly_bar.py

Closes #1667 
As pointed out in the related issue there were at least two examples that didn't work either from differences between PyQt4 to PyQt5 or changes to vispy over time.
1. `primitive_mesh_viewer_qt.py`: Depending on your system this demo would cause GL errors or have Qt complain about a recursive event loop. After some debugging I discovered that this was caused by the statusBar in the widget being used to show the FPS of the canvas. The example was updating the FPS display for every draw event (as is traditionally done) by using the status bar's `showMessage`. For some reason `showMessage` is triggering another immediate draw event; perhaps to show the status message as quickly as possible. The fix is to use a QLabel that is added to the statusBar and update its text. This …

Fix primitive_mesh_viewer_qt.py and wiggly_bar.py examples

---

examples/demo/gloo/molecular_viewer.py

Closes #1642 
Some systems/GPUs seem to default to a non-opaque alpha value. This fixes this example where it was noticed that this was happening and causing weird results.

Fix transparency in molecular_viewer on some machines

---

MANIFEST.in
azure-pipelines.yml
setup.py
vispy/__init__.py

This PR updates the azure configuration to:
1. Add sdist generation
2. Upload the sdist and all wheels to PyPI
This works by setting a special variable in the Azure web UI with a PyPI API token under my account. This token only has access to upload to the vispy project on PyPI, will do it as me, and the secret variable can only be seen by people who have permission on the azure vispy project. By setting the environment variable `TWINE_PASSWORD to this value `twine` should pick it up and use it to upload the packages.
The main thing I think I have wrong is that all the wheels and the sdist file are uploaded to the "wheelhouse" artifacts storage, but I don't think I can access that as a simple directory in a separate job (see the `twine upload` call). If there is no way to do that then I …

Add automatic PyPI deployment through Azure

---

examples/demo/gloo/boids.py
examples/demo/gloo/cloud.py
examples/demo/gloo/donut.py
examples/demo/gloo/fireworks.py
examples/demo/gloo/galaxy.py
examples/demo/gloo/galaxy/galaxy.py
examples/demo/gloo/galaxy/galaxy_simulation.py
examples/demo/gloo/graph.py
examples/demo/gloo/molecular_viewer.py
examples/demo/gloo/quiver.py
examples/demo/gloo/rain.py
examples/demo/gloo/signals.py
examples/tutorial/gl/fireworks.py
vispy/gloo/buffer.py
vispy/gloo/program.py
vispy/visuals/markers.py
vispy/visuals/windbarb.py

In future versions of numpy defining a dtype as `('name', np.float32, 1)` will be interpreted differently. You currently get this warning:
```
/home/travis/build/vispy/vispy/vispy/visuals/markers.py:564: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
('a_edgewidth', np.float32, 1)])
```
I fixed a couple of these after it was pointed out by some napari developers, but these should be all the rest now that travis can complain about them.
If I remember correctly vispy is currently using `, 1)` as "scalar" and in the future this will be treated as a length 1 array. But now I don't remember what `, 0)` means.

Fix numpy futurewarning in dtype creation

---

azure-pipelines.yml

PyPI tokens are still in beta and in a recent update they've changed how they would like upload tokens to be provided and used.
```
username:       @token                          =>      __token__
password/token: pypi:<base64 token body>        =>      pypi-<base64 token body>
```
Because I made the Variable on Azure secret I couldn't simply modify the value of it so I had to make a whole new token under my account on PyPI. The token is now updated on Azure and this PR makes vispy use the new token.

Update azure PyPI token to match new standards

---

vispy/visuals/markers.py

Replace 'assert' by an 'if' when pos is None. This prevent constructors depending on markers to crash with None data -> For example LinePlotVisual was crashing with data=None.

Fix MarkersVisual.set_data crash when pos is None

---

.gitignore
pyproject.toml
setup.py
vispy/__init__.py
vispy/util/tests/test_import.py

This updates vispy's version number handling to be automatic based on git tags instead of having to manually edit the value in `vispy/__init__.py`. The one major change to this is that `setup.py` no longer updates the `__doc__` attribute of `setup.py`, but I don't see the point of this anyway. This is even less useful now that `pip install` (and variants) is the preferred method of installing python packages instead of `python setup.py ...`.
More info on setuptools_scm: https://pypi.org/project/setuptools-scm/
Requires https://github.com/vispy/vispy-website/pull/26
Note: In previous non-github conversations I had mentioned "caching" the version number in something like a `vispy/version.py` file. I was going to try this with my Satpy library but one of the other maintainers didn't like it. …

Switch to setuptools_scm for automatic version numbering

---

.git_archival.txt
.gitattributes

This was a small thing I missed from #1706. I added the `setuptools_scm_git_archive` package so that if someone installs from a release from github it will include the necessary information to determine what the version number should be. However, I forgot to actually do the part where it includes that information :smile:
This PR fixes that by following the installation instructions described [here](https://github.com/Changaco/setuptools_scm_git_archive/).

Fix setuptools_scm_git_archive usage

---

vispy/visuals/volume.py

When I try to use my own colormap using 
```python
n_colors = 256
t = np.linspace(0., 1., n_colors)
color = np.c_[t, t, t, t*0.05]
cmap = Colormap(color)
```
instead of the one from `examples/basics/scene/volume.py`
```python
class TransGrays(BaseColormap):
glsl_map = """
vec4 translucent_grays(float t) {
return vec4(t, t, t, t*0.05);
}
"""
```
it keeps showing 
> Program has unset variables: {'texture2D_LUT'}  
with a blank screen.
Not sure if this is the best way to do it, after comparing how `cmap` is configured in `visuals.Image`, `visuals.Mesh`, `visuals.Colorbar` and `visuals.Line`, I think `texture2D_LUT` is missing.

Volume visual has unset variable texture2D_LUT

---

vispy/app/canvas.py

Fixes #1729. If I understood correctly the `RuntimeError`, an alternative to `keys.pop(key)` should solve this.

Fix Python 3.8 compatibility in Canvas 'keys' update

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This PR copies data by default in `VolumeVisual.set_data`, and adds a copy parameter to the method for those who want to maintain the existing behavior (wherein float32 data is not copied).
see #1727 for full discussion.

Fix VolumeVisual modifying user provided data in-place

---

azure-pipelines.yml

See https://github.com/vispy/vispy.js/pull/26 for details.
Basically for the 0.6.2 release I had to hardcode the version number so setuptools_scm would be happy. I have now updated the vispy.js repository so it doesn't include the `package-lock.json` file which was being updated during setup.py building and causing issues with the version number that `setuptools_scm` ended up generating.

Update vispy.js to not include package-lock.json

---

vispy/visuals/markers.py

This PR fixes #1166 where the scale was not working properly for markers when they were being rotated.
Please see that issue for a detailed discussion of the problem and proposed solution, including example code to reproduce the bug and gifs of the behavior before and after the fix.

Fix MarkerVisual scaling when rotating in 3D space

---

azure-pipelines.yml
setup.py
vispy/gloo/glir.py
vispy/gloo/tests/test_glir.py

Closes #1755
The WebGL shader handling currently removes the version directive from the shaders before they're sent to the client. This is maybe not the best long term solution, but this is the way I made it a while back.
Anyway, the code that removes the version directive from shader code also inserts certain `precision` directives which are required in webgl. Version directives, if they exist, must be the first line in a shader appearing before precision directives. Precision directives must also appear before code. It seems that I never tested this logic with a shader that actually includes a version directive since there is a bug where `precision` lines are being reinserted *after* the first line of code. This PR fixes this.

Fix shader version handling in webgl backend

---

vispy/gloo/glir.py
vispy/gloo/tests/test_glir.py
vispy/gloo/texture.py

See https://github.com/napari/napari/issues/576 for the main discussion of this.
When writing or reading data to/from the GPU with OpenGL we need to specify the row alignment of our data. For writing data to the GPU we set the "GL_UNPACK_ALIGNMENT" parameter to 1, 2, 4, or 8. This tells OpenGL if the next row of data will be in the next byte, next 2-bytes, 4-bytes, or 8-bytes.
**Edit for clarification:** I meant the next aligned 2-bytes or 4-bytes, or 8-bytes. So if the data goes up to byte 30 and our alignment is 8 then OpenGL will get our next from starting at byte offset 32.
In general Vispy requires or copies the data it is given by the user to be memory contiguous. So you might argue that the alignment can always be 1 (the next row starts in the next immediate byte). It isn't clear, …

Fix texture alignment to use data itemsize

---

vispy/scene/cameras/fly.py

See issue #1554. The bug is fixed as discussed.
- Replaced actual `rotation.setter` function by a warning of using `rotation1.setter instead`
- Added property `rotation1` and `rotation1.setter`
- Added property `rotation2` and `rotation2.setter`
- Normalizes Quaternion before assigning.

Fixed a bug in linking two flycameras

---

vispy/visuals/axis.py
vispy/visuals/tests/test_axis.py
vispy/visuals/tests/test_text.py
vispy/visuals/text/text.py

This fixes a few bugs I ran into while using ``AxisVisual``:
* Changing the ``.rotation`` on a ``TextVisual`` didn't previously update the actual shader attribute for rotation. This became apparent when rotating the axes in 3-d, as the labels didn't follow the rotation.
* The calculation of the angle for the axis label didn't quite work when projection is present
* Warnings were emitted when the min/max for axes were the same
It's not clear to me how to properly test the first two but I think I could add a test for the last one if needed.

Bug fixes related to AxisVisual

---

vispy/visuals/collections/collection.py

These were missed by #1691 but I started noticing them in some recent PR CI tests.

Fix additional numpy warnings when dealing with dtypes of size 1

---

vispy/plot/plotwidget.py
vispy/plot/tests/test_plot.py

This PR Fixes #1742 by adding the xaxis `AxisWidget` to the `PlotWidget.grid` before the `ViewBox` gets added.
Explanation (hope this is clear):
The order that widgets get added to the `PlotWidget.grid` in `PlotWidget._configure_2d` is currently problematic, because the xaxis `AxisWidget` (but not the yaxis `AxisWidget`) is getting added to the grid after the `ViewBox` is added.  As a result, when the `Grid._prepare_draw` method triggers `Grid._update_child_widget_dim` and it [loops through the grid widgets](https://github.com/vispy/vispy/blob/6f4e52aeecc40c29bf2fde3d217c0a3e6ea6b438/vispy/scene/widgets/grid.py#L481-L502) to update their sizes, the `ViewBox` `rect.setter` gets called before the xaxis `AxisWidget` has had a chance to update its size.  It is the `ViewBox` `rect.setter` that …

Fix xaxis labels being wrong initially in PlotWidget

---

vispy/visuals/transforms/_util.py

Fix `TypeError: not all arguments converted during string formatting`

Fix string formatting of array shape

---

.travis.yml
vispy/visuals/tests/test_axis.py

Attempt to fix #1765 
First thing I'm noticing is a difference in pytest version. Pytest 5.3.0 got some work done on caching test files in python 3.8 so you would think that wouldn't be a problem since we are using python 3.7, but maybe it is.

Fix failing travis CI OSX test failures

---

.gitignore
MANIFEST.in
pyproject.toml
setup.py
vispy/__init__.py
vispy/util/tests/test_import.py

Closes #1779 
This switches vispy to use a feature of setuptools_scm which writes the generated version number to a `vispy/version.py` file. This is different from what was previously done which was to use setuptools to read the installed package's metadata and extract the version number. As discussed in #1779, this can cause major overhead on systems with a lot of packages installed. This PR is the simplest workaround for that.
The downside to this is that developers installing vispy in a "development mode" may be confused by a `vispy/version.py` that is ignored by `.gitignore` and was generated just by them installed the package.
This starts to put in place some functionality that setuptools_scm recently documented and added to enable setuptools_scm from the pyproject.toml file. …

Switch to setuptools_scm version.py usage to avoid import overhead

---

vispy/util/fonts/tests/test_font.py

Fixes: https://github.com/vispy/vispy/issues/1771
Also uses fixtures so as not to change the global state of the the warnings filter.

Skip bad font in test_font

---

.travis.yml
appveyor.yml
azure-pipelines.yml
vispy/app/backends/_glfw.py
vispy/app/canvas.py
vispy/app/tests/test_app.py
vispy/testing/_runners.py
vispy/testing/_testing.py
vispy/visuals/axis.py

Hopefully makes GLFW 3.3.1 tests work. I think they might have some bug with `decorate` as not setting the value makes things pass on my system (at least on 3.4.0 dev that I installed). Probably worth filing an upstream bug if this actually works.
EDIT: Also replaced Travis custom setup with cleaner `ci-helpers` interface
EDIT: Also silenced some errors about bad division in `axis` tests
EDIT: Also configured Travis's runs to use `--tb=short` to shorten tracebacks

MAINT: GLFW workaround

---

examples/basics/visuals/text_visual.py
vispy/visuals/tests/test_text.py
vispy/visuals/text/text.py

For a use case I have, I needed to be able to find out whether a ``Text`` object had a bold font, and needed to be able to set it, so I decided to add properties for the face, bold, and italic properties of Text (since these can be set via the ``__init__``, I thought having properties that match these arguments would make sense).

Make it possible to get and set the face, bold, and italic properties of Text via properties

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This PR adds an `interpolation` property to the Volume visual and exposes a `nearest` and `linear`. It defaults to the `linear` behavior, which is what is currently supported, but provides the option for a `nearest` - which is particularly useful when viewing discrete (say integer labeled) regions in 3D.
Before with `linear`:
Now with `nearest`:
You can see these in use here https://github.com/napari/napari/pull/841 too
This PR adds documentation for the new property and a test for it.

Add nearest interpolation to volume visual

---

.gitignore
README.rst

Refer to documentation on the website instead.

DOC: Drop installation instructions from readme

---

.travis.yml
appveyor.yml
vispy/util/fetching.py

The VisPy cron job for Travis CI is failing on OSX. Not sure why specifically OSX, but while investigating I noticed that the GitHub raw file URL gets redirected. This PR changes VisPy's default download URL to be this new base URL. Let's see if the tests pass with it...

Fix GitHub raw file download base URL

---

vispy/gloo/buffer.py

The `offset` is in "item count" unit not in "byte count" unit as is the case in the dtype-agnostic `Buffer` class.
The doc was probably copied over from the `Buffer` class without adaptation.

Fix DataBuffer.set_subdata docstring with wrong offset units

---

.travis.yml
azure-pipelines.yml
vispy/gloo/tests/test_glir.py
vispy/plot/tests/test_plot.py
vispy/testing/_testing.py

I get that moving backends is a "decision" that must be thought of. 
This is just a little fix that enables decorators to be stacked and used with pytest.
Otherwise, enabling the gc destroys other pytest decorators.

Fixup decorator to enable full use of pytest.

---

examples/basics/scene/isocurve_for_trisurface_qt.py
examples/demo/gloo/primitive_mesh_viewer_qt.py
examples/demo/visuals/wiggly_bar.py

While most of examples/demos have hardcoded PyQt5 usage, it is generally trivial to pass to PySide2 by just replacing PyQt5 with PySide2 in the imports. But there are a few exceptions, like the two demos touched by this PR, that use signals where the PyQt5 and PySide2 API differs. 
This PR makes also those demos easily switchable.
I'm not sure a general revision of demo code, or just a plain explanation, would be advisable given that PySide2 is getting more important with the backing of Qt. 
If so I can try to contribute in this sense.
Federico

Make demos easier to switch to PySide2 from PyQt5

---

vispy/visuals/volume.py

This PR improves the isosurface rendering in the volume visual by getting rid of the default greenish tinge that was always being applied and allowing the isosurface to also respond to the changing of the colormaps. You can see it in action here https://github.com/napari/napari/pull/840 and below.
Original behavior:
Improved behavior:
I realize this change will change how peoples renderings currently look, but I hope the majority of people will find the new behavior and improvement.

Remove isosurface green color in VolumeVisual

---

azure-pipelines.yml

Build wheels against more modern standards allow to use newer compilators and api which my produce better/faster shared libs. So I suggest to add builds of manylinux2014 and macos 10.14 wheels.

Add MacOS 10.14 and manylinux2014 wheel builds

---

vispy/visuals/line_plot.py

Currently, if someone generates a line plot with no markers, for instance:
```python
line = scene.LinePlot((x,y), marker_size=0)
```
and then later updates the data with 
```python
line.set_data((x,y/2))
```
the markers come back.
This PR modifies the behavior of `LinePlotVisual` visual slightly to store the styles set during `__init__` or calls to `set_data`, such that styles do not need to be repeatedly given to `set_data` if one only wants to update the data itself.

Fix LinePlotVisual not remembering styles

---

.travis.yml
appveyor.yml
azure-pipelines.yml
setup.py
vispy/io/mesh.py
vispy/io/tests/test_io.py

A rather unintrusive introduction of meshio into `read_mesh`. One could go further and have all i/o handled by meshio; obj and stl readers are in place. I didn't want to stretch it too far for this first PR though.
What works now:
```python
import vispy.io
verts, faces, _, _ = vispy.io.read_mesh("triceratops.vtu")
```
with all meshio-supported formats (there are around 30) _if_ meshio is installed and the mesh does in fact contain triangles.
Fixes #1817.

Use meshio fall back for reading and writing mesh files

---

vispy/visuals/image.py
vispy/visuals/tests/test_image.py

This is a companion to #1842.  It puts (re)calculation of contrast limits (and adds gamma) to the `ImageVisual` shader.  If `clims` are changed after the `ImageVisual` has been created, then the texture will only be rebuilt (`_need_texture_upload == True`) if the new `clims` are outside of the bounds of the previous clims.  (note: unlike `VolumeVisual` in #1842, `ImageVisual` holds a copy of the data, so rescaling is easier).
possible embellishments include: allowing gamma and/or contrast limits to be set _per_ channel (for an rgb image).

Add ImageVisual gamma and smarter in-shader contrast limits

---

vispy/visuals/image.py
vispy/visuals/tests/test_image.py

While looking at #1852 I noticed that the ImageVisual is updating the vertex and texture coordinates during *every* draw. This PR should fix that.
TODO:

Fix ImageVisual updating vertex coordinates on every draw

---

vispy/gloo/glir.py
vispy/gloo/program.py

I added lines_adjacency and line_strip_adjacency OpenGL primitives, so I can emulate quads with geometry shader.
[https://github.com/proto3/vispy/blob/quad-gif/quad.gif](https://github.com/proto3/vispy/blob/quad-gif/quad.gif)
It worked immediately with GL+ backend, but it won't with GL2 so it raise an explicit error advising to use GL+ with these primitives.
In the mean time, I updated the geometry shader support error message, so it won't blame 'GL2' all the time but gl.current_backend.__name__

Add lines_adjacency and line_strip_adjacency OpenGL primitives.

---

vispy/visuals/axis.py
vispy/visuals/visual.py

I am starting to work with the `PlotWidget` a bit more for use in `napari`.  This is a small PR, partially for that and also to fix part of https://github.com/vispy/vispy/pull/1748#issuecomment-559789319.  It modifies `AxisVisual` to ensure that all of the parameters in the `__init__` method can be easily changed as attributes/properties after instantiation, and that changing them immediately updates the necessary subvisuals.
Rather than make a whole bunch of relatively empty `@property` and `@setter` methods just to set `_need_update` and call `self.update()` each time, I chose to modify the `__setatr__` method instead, calling `update()` for all parameters that wouldn't have otherwise induced a visual update.  (Note, parameters that are _not_ listed in there, such as `tick_width`, …

Make all AxisVisual parameters easily updatable after instantiation

---

vispy/app/backends/_ipynb_webgl.py
vispy/app/backends/ipython/_widget.py
vispy/app/canvas.py

This PR adds the ability to pass arguments into the webGL context creation function by setting an attribute of the `VispyWidget` before showing the `Canvas`. I'm interested in doing this (or something like this) to be able to set `preserveDrawingBuffer` of the created contexts, so I can "freeze" vispy notebook widgets as static images that can be saved in the notebook itself (see [vispy_toDataUrl.ipynb.txt](https://github.com/vispy/vispy/files/3498482/vispy_toDataUrl.ipynb.txt) for an example). The easy solution would be to just always set `preserveDrawingBuffer` in vispy-created contexts, but I have read that it can carry a performance penalty of around 50% on some very weak hardware (like phones). 
I'm not terribly familiar with vispy's internals, but I imagine there is a better way to …

Add ability to pass webGL context arguments for notebook backend canvas initialization

---

examples/basics/scene/mesh_texture.py
vispy/visuals/filters/__init__.py
vispy/visuals/filters/base_filter.py
vispy/visuals/filters/mesh.py
vispy/visuals/mesh.py

This PR implements texture support for MeshVisual as a filter.
Addresses #748 
Edit(2018-11-05): Update following #1462 enforcing unindexed buffers for meshes.

Add TextureFilter for adding textures to MeshVisuals

---

.travis.yml
vispy/color/color_array.py
vispy/color/tests/test_color.py

fix #1858 with adding check if any list member is instance of `Color` or `ColorArray`

Fix creating colormap from list of Color objects

---

vispy/visuals/mesh.py

MeshVisual currently seems to always reindex the vertex array as face-indexed vertices. This should rather be the decision of the caller for practical and perfomance reasons (e.g., glDrawEelements vs glDrawArrays).
This PR changes the behavior of MeshVisual to use whatever indexing was provided by the caller.
This allows the implementation of texture filters (#1444) and coming-up shading filters without workarounds.

Fix mesh indexing mode

---

vispy/scene/cameras/arcball.py
vispy/scene/cameras/perspective.py
vispy/scene/cameras/turntable.py

In Base3DRotationCamera, instead of gradually constructing the view
matrix inside MatrixTransform, do prepare the final matrix first, then
assign it to MatrixTransform.
This is done to avoid the relatively costly operations each time the
matrix inside MatrixTransform changes.
See #1878.

Speed up arcball and turntable cameras

---

vispy/scene/widgets/grid.py

This PR i a fix when we use Fig class to create a grid.
There is a bug if you write
```
f = Fig()
ax = f[0]
...
```
Then the cspan is 0. The PR solves the problem by giving a default size to 1 for the column.
This PR adds also a _row_widgets that defines the widgets that take all the row and need to be expand when the column size of the grid has changed.
The idea is to have the same behavior if you do
```
f = Fig()
ax1 = f[0]
...
ax2 = f[1, :2]
```
or 
```
f = Fig()
ax1 = f[0, :2]
...
ax2 = f[1]
```
I think that we have to change also the stretch of the widget when we change the size of the cspan of the _grid_widgets in _update_child_widgets but if I do that I have a "maximum recursion depth exceeded" because modified stretch call again _update_child_widgets.

Fix grid_widget when Fig gets a single element

---

codegen/annotations.py
codegen/createglapi.py
codegen/headerparser.py
vispy/gloo/gl/_pyopengl2.py

- Fix codegen so that opengl correctly parses annotations with backend
set to 'es'.
- Actually fix commit 3dd6018d1cd79c1ca828526d377c5c880f168a0e so that
it is applied in codegen and not by modifying an auto-generated file.
- Adds syntax "# /---" to stop backend selection in annotation parsing.
- This also properly fixes what was attempted with pull request #1273.

Fix codegen backend selection and fix PyOpenGL glGetParameter.

---

README.rst
azure-pipelines.yml
vispy/testing/_runners.py

Tests on appveyor and Azure started failing all of a sudden and it seems to be related to how arguments are passed from vispy's `_runners.py` module to the python executable through `run_subprocess`.
```
_VISPY_TESTING_APP=nobackend C:\conda\envs\test\python.exe -m pytest -m "not vispy_app_test" --cov vispy --cov-report= -ra c:\projects\vispy\vispy
============================= test session starts =============================
platform win32 -- Python 3.7.9, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: c:\projects\vispy, configfile: pytest.ini
plugins: cov-2.10.1, sugar-0.9.3
collected 470 items
============================ no tests ran in 2.96s ============================
ERROR: Wrong expression passed to '-m': "not vispy_app_test": at column 1: unexpected character """
Failed: unit …
```

Fix test runners not passing arguments properly on Windows

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This began as an internal PR at https://github.com/napari/napari/pull/1056, but I'd like to know if it's something you would consider.  In typical [napari](https://github.com/napari/napari) usage, it would be pretty normal to repeatedly change the min/max contrast limits while viewing a 3D volume.  Unfortunately, each change incurs a renormalization on the CPU in [`Volume.set_data`](https://github.com/vispy/vispy/blob/3ac28ff0daf8836b44c6eba8d3c98541e37c5702/vispy/visuals/volume.py#L487-L493), leading to very laggy performance.  This PR moves most of the _re_-calculation of clims to the shader as follows:
- `Volume.clim`→ `Volume.clim_range`: `Volume.clim` was previously just serving a one-time role of data normalization (0-1) prior to moving the volume to Texture memory.  Seems to me …

Implement volume contrast limits in shader, add gamma

---

vispy/visuals/image.py

fixes a bug resulting from #1844  that can cause inconsistent contrast (only in specific cases) in when rebuilding an image texture with `ImageVisual._build_texture()`  (originally observed/described at napari/napari#1585)

Fix ImageVisual not updating color transform after texture update

---

azure-pipelines.yml
vispy/io/datasets.py
vispy/io/image.py
vispy/io/tests/test_io.py

I inspected the latest azure CI run on master and saw the same issues related to `numpy`. I fixed what was reported in `vispy/io/image.py` and `vispy/io/tests/test_io.py`. I also found a usage of `tostring()` in `vispy/io/datasets.py`.
Closes https://github.com/vispy/vispy/issues/1909

Fix various numpy deprecation warnings

---

vispy/geometry/torusknot.py

The `fractions.gcd()` function has been removed in Python 3.9. It was deprecated since Python 3.5: use math.gcd() instead. See https://docs.python.org/3.9/whatsnew/3.9.html#removed

Fix ImportError on Python 3.9

---

vispy/geometry/rect.py
vispy/scene/cameras/base_camera.py
vispy/scene/cameras/tests/test_link.py

I suggest adding an argument to BaseCamera.link letting the user specify the camera properties to be linked.
The use case I have in mind is two turntable cameras with only the elevation and azimuth, not the scale_factor, being linked.

Let camera link be limited to specified properties

---

.travis.yml
ci/build_website.sh
vispy/testing/_runners.py

This is an attempt to get travis to build the vispy website and upload it to the vispy-website repository. It was recommended that we look at doctr for handling the upload and deploy key handling (https://github.com/drdoctr/doctr). One nice thing about that would be this extension that allows us to have multiple versions like readthedocs allows (https://github.com/goerz/doctr_versions_menu).
I can't promise I'll get to it (maybe a good hacktoberfest issue), but here are the current issues I see when I build the site locally:
```
/home/davidh/repos/git/vispy/_website/conf.py:352: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
app.add_stylesheet('css/font-mfizz.css')
/home/davidh/repos/git/vispy/_website/conf.py:353: …
```

Add website building to travis tests

---

vispy/ext/egl.py

eglTerminate had the docstring of eglInitialize. Now replaced with the docstring as used in https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglTerminate.xhtml

Fix EGL docstring copy/paste error

---

.travis.yml
appveyor.yml
setup.py
vispy/app/backends/__init__.py
vispy/app/backends/_tk.py
vispy/app/tests/test_app.py
vispy/app/tests/test_context.py

For my current project, it would be beneficial to be able to use VisPy within a Tkinter context, i.e. an OpenGL canvas controlled by VisPy embedded inside a Tkinter widget (tk.Frame).
For this purpose, I attempted to create a new backend to target Tkinter. However, it needs more work to to actually draw something.
The implementation tries to use [Jon Wright's pyopengltk](https://github.com/jonwright/pyopengltk) `OpenGLFrame`.
You can refer to [this Gist with example code](https://gist.github.com/Wosser1sProductions/620d2422a8a2f2529d01bf34e229d7ca) that shows how I might use it. For reference, everything works as expected using the Glfw backend, but this creates a new window naturally.
Using the tkinter backend, creates the frame that can be embedded, but it seems to stay black. Running …

Add Tkinter backend

---

vispy/ext/cocoapy.py

Adapted stackoverflow monkeypatch to ctypes.util.find_library for macOS 11 (Big Sur).
This gates off OpenGL.GL dlopen failure and uses a 2-entry lookup for quartz and objc exception cases. 
Should be backward compatible and is likely to work on both x86 and and m1 macOS.
Tested on x86 macOS 11.1 with `alpha-pyside2.py` test case.

Add workaround for MacOS dlopen

---

vispy/plot/fig.py

(previously forced to 'interactive' in call to super().__init__()).
I couldn't figure out how else to pass key events up to a PyQt5 QMainWindow.

Changed vispy.plot.Fig.__init__() to allow passing 'keys' argument

---

examples/basics/scene/shape_draw.py

Following up on the line_draw example, this is a slightly more advanced example which lets the user draw rectangle and ellipse visuals interactively with the mouse, resize them using control points, move and delete them. It demonstrates the use of visual_at, adding and modifying visuals in a scene, mouse handling and transformations. It also has shapes at fixed positions (not zooming/scrolling with the scene) which are used as "buttons" to select the edit mode. It is meant as a starting point for more complex interactive mouse-driven vector drawing applications.
I have some questions for the maintainers: 
- currently this example is in examples/basics/visuals, because that's where the line_draw example was, and where I found the line_plot and polygon_visual examples that served as …

Add new example for mouse editing/drawing of shapes

---

vispy/app/backends/_qt.py

Those two are supposed to hold the total scale change and rotation
change since the beginning of the touch event, and are easier to
manipulate than to accumulate the delta changes.
Note that testing locally on MacOS 10.12 using a macbook pro with a
touchpad the rotation does not seem to follow the description of the Qt
framework. That is to say:
- event.rotation: total rotation since begin event
- event.scale: Change of scale since last event, generally between 0.95 and 1.05.
- totalRotationAngle: Always 0 for me
- totalScaleFactor: Total change of scale change since evt.type=begin event.
I still include those two, as in particular it seem on some devices you
can "interrupt" and "restart" a gesture; especially for rotation, and
even if totalRotationAngle seem broken on my end; …

Add totalRotationAngle and totalScaleFactor to touch (pinch) events.

---

examples/basics/scene/mesh_shading.py
vispy/visuals/filters/mesh.py
vispy/visuals/tests/test_mesh.py

That is, this draws only the interior of the faces.
Named the attribute `faces_only` to match `wireframe_only` previously defined. Maybe there is a better-suited naming, `transparent`?
Follow-up on #2025

Add the ability to make the wireframe transparent with the wireframe filter

---

examples/basics/scene/mesh_shading.py
examples/basics/scene/mesh_texture.py

The command line parsing in the examples was failing because it was receiving
the arguments from `python make image gallery`.

Adapt mesh examples for gallery image generation

---

.github/workflows/main.yml

I noticed while working on another project and copying from VisPy that the commit messages weren't actually rendering the environment variables I was trying to use. I think this PR should fix these (currently testing with the geoxarray project).

Fix website deploy commit message references

---

vispy/visuals/volume.py

Starting gently after our discussion last week, here's a small PR introducing minimum intensity projection shading as a rendering mode for the `VolumeVisual`. This was introduced into napari in napari/napari#1861 and can be seen there, sorry for the wait in pushing upstream!

Add minimum intensity projection (minip) shading to `VolumeVisual`

---

vispy/visuals/volume.py

In an ongoing effort to upstream changes to the `VolumeVisual` made in napari here is the average intensity projection volume rendering introduced in napari/napari#1871
This addition will be covered by tests @djhoese added in #1912

Add average intensity projection (average) rendering mode to `VolumeVisual`

---

vispy/app/backends/_glfw.py

Closes #1465 
This is the simplest fix or workaround I could find for the various bugs related to glfw not handling the initial size of a window properly. As mentioned in #1465 I don't think this should break anyone's workflow as it shouldn't have worked before anyway and is just an extra vispy resize event. I'm not sure how to test this as it seems using `canvas.render()` which is used in all our tests that actually render something puts things into a proper state because it push/pops viewports which makes calls to `self.context.set_viewport` and `self._update_transforms` and makes the visuals draw correctly. These same methods are called from the `on_resize` method and is the only reason other backends like pyqt work properly. If I turn off the resize handling and run with pyqt I get …

Fix glfw not sizing visuals correctly on initial draw

---

vispy/glsl/lines/agg.vert
vispy/visuals/line/line.py

Closes #1441. This changes the agg-line vert shader so that it writes the correct value to the depth-buffer. However, 
we can't really turn on depth testing by default because it will cause weird artifacts at the edges. This is part of the general problem of blending translucent objects ...
Neverthertheless, when needed the depth test can be turned on. The example in #1441 then becomes:
```py
import sys
from vispy import app
from vispy.io import load_data_file, read_png
from vispy.visuals.transforms import STTransform
canvas = scene.SceneCanvas(keys='interactive')
canvas.size = 800, 600
canvas.show()
view = canvas.central_widget.add_view()
img_data = read_png(load_data_file('mona_lisa/mona_lisa_sm.png'))
interpolation = 'nearest'
pos = …
```

make agg lines write correct depth value

---

vispy/util/event.py
vispy/util/tests/test_event_emitter.py

Delay checking if stuck in an event loop until after checking if the event emitter is being blocked. This allows callback cycling. 
Toy example:
```python
e = EventEmitter(source=None, type='test')
def foo(x):
print('foo')
with e.blocker():
e()
e.connect(foo)
e()
```
However, this check can be erroneously triggered during asynchronous operations. IMO if there is no real good reason for the check (since the loop will automatically trigger a `RecursionError` anyways), I'd like to just flat-out remove it.

Fix event loop detection triggering on blocked events

---

examples/basics/visuals/colorbar_visual.py
examples/basics/visuals/colorbar_visual_types.py
vispy/scene/widgets/colorbar.py
vispy/scene/widgets/tests/test_colorbar.py
vispy/visuals/colorbar.py
vispy/visuals/tests/test_colorbar.py

Let's try this again. This is a replacement for #2056 which after trying to rebase and merge just got too ugly with commit history. I instead copied the current state of #1292 into a new branch and committed with @macrocosme as the author of the commit.
Updates .label property so it can be provided a TextVisual or a new string to update the existing TextVisual of a ColorbarVisual.
This is a replacement for #1292 so that I can actually make commits to it (compared to the original fork's master branch).
I'll need to reapply the style fixes from `main`.

Add setter for colorbar label text

---

examples/basics/scene/mesh_shading.py
vispy/visuals/filters/mesh.py
vispy/visuals/tests/test_mesh.py

Expose the Phong model coefficients with reasonable defaults and allowing for fine-grained control:
- `shading='flat'`
- `light_dir=(10, 5, -5)`
- `ambient_light=(1, 1, 1, 0)`
- `diffuse_light=(1, 1, 1, 1)`
- `specular_light=(1, 1, 1, .25)`
- `ambient_coefficient=(1, 1, 1, 1)`
- `diffuse_coefficient=(1, 1, 1, 1)`
- `specular_coefficient=(1, 1, 1, 1)`
- `shininess=100`
The light and reflection coefficients are RGBA where A controls the intensity. In most cases, one will only adjust the intensity (e.g. dimming the (white) light and modulating the strength of the reflection).
TODO:
- ~~[RFC @djhoese ] Require light position, `light_pos`, as input parameter instead of light direction, `light_dir`. This will allow different types of lights in the future. Deprecate `light_dir`.~~ EDIT: Forget …

Identify and expose Phong shading parameters in mesh ShadingFilter

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This is a partial fix for #2064 (CC @yxdragon).
The issue is that the VolumeVisual assumes data is in the shape of `(z, y, x)`, but VisPy seems to assume that axis (0, 1, 2) -> (x, y, z). We can see this in the `ImageVisual` which passes data as `(y, x)` and in its `_compute_bounds` method it uses `self.size` which is the reversed shape of the array. So the bounds are computed accurately. For the VolumeVisual, we need to take these values in reverse as well (but aren't currently). This PR does this by using in a way so if a VolumeVisual ever has more than 3 dimensions, the last 3 dimensions are used. I'm not sure that is a bad assumption or not bug :shrug: 
Also, I've added a `self._is_zyx` property to the `VolumeVisual` so that in the future the rest of #2064 can be resolved in which a …

Fix VolumeVisual bounds representing the wrong axis

---

vispy/color/colormap.py
vispy/visuals/tests/test_colormap.py

Closes #1487 
Some of the colormaps available through `vispy.color.colormap.get_colormap` were classes that were created when `get_colormap` was called with optional args, kwargs provided. This has always smelled bad to me code-wise. In this PR I create instances of the colormaps as replacements and deprecate ones that are redundant.
One consideration: should I just remove all of these instances, list them as deprecated, and then rename the classes to not be prefixed with `_`? So `_SingleHue` becomes `SingleHue` and if a user wants to create this colormap they can import it, create it, and pass it directly.
Edit: I have not updated the tests which seem to test some of these specifically.

Change builtin colormaps to all be instances

---

vispy/scene/cameras/panzoom.py
vispy/scene/cameras/tests/test_perspective.py

Replaces #1751. I tried to rebase that PR on to `main` and git (or rather pycharm) warned me that it wasn't going to end well. I instead created a new branch off of `main` and cherry-picked it since it was a single commit. I've then modified how the `DEFAULT_RECT_TUPLE` was defined as flake8 was pointing out that it isn't actually available in the internal method scope.
Now to write a test... :fearful:

Fix PanZoomCamera 'center' property not updating view

---

vispy/visuals/filters/mesh.py

With these changes, the ambient light is:
- on by default with intensity 0.3,
- applied on the base color of the mesh.
The restores the behaviour of the MeshVisual as before the ShadingFilter was introduced.

Restore ambient light behavior as in v0.6.0

---

examples/collections/path_collection.py
setup.cfg
vispy/app/backends/_tk.py
vispy/gloo/wrappers.py
vispy/visuals/collections/agg_fast_path_collection.py
vispy/visuals/collections/agg_path_collection.py
vispy/visuals/line/line.py

* Make flake8 ignore `N` in case the pendantic "pep8-naming" is installed.
* Check for imports of `OpenGL`:
* Removes use of `OpenGL` in `visuals/line/line.py`.
* Remove use of `OpenGL` in  `backends/_tk.py`.
* No other usages.
* Check for usage of `gl` in visuals and above:
* It is used in path collections to disable the depth buffer. Seems hard to fix, so added a comment for now.
* No other usages.

Close some GL leaks

---

examples/basics/plotting/volume.py
setup.cfg
vispy/plot/plotwidget.py
vispy/visuals/_scalable_textures.py
vispy/visuals/image.py
vispy/visuals/tests/test_scalable_textures.py
vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

* The logic in the shader is simplified and has no branches (in the clim computation).
* Deal with nan and inf in data. Uses @larsoner's idea to stay performant by default at the cost of being a bit extra less performant when non-finite values are present :)
* Correct behavior when clim range is zero.

Improve infinity/NaN handling in VolumeVisual and ImageVisual clim calculations

---

vispy/scene/node.py

This is a possible cleanup as discussed in #2083. This assumes a lot of stuff about VisPy and Python garbage collection that may not actually matter. I kind of ran wild with this idea that VisPy is adding a reference to a Visual that never gets collected. I tracked it down to the `self.scene_node` property of the Node class (used by SceneCanvas graph nodes). The behavior that I was trying to "fix" was that when you set a parent for a Node and then remove that parent you should end up with the same number of references for that Visual. This may not matter or be wrong because:
1. I don't think Python garbage collection cares about an object referencing itself.
2. I'm not sure if this will break certain cases of using VisPy where the `.scene_node` should be a "hard" reference...but I'm not …

Fix SceneCanvas Node leaking reference to itself

---

examples/demo/gloo/realtime_signals.py
examples/demo/scene/scrolling_plots.py

Closes #1871
The problem is that if updates are done, these are encoded as GLIR commands, which end up in a queue. You can imagine that this queue becomes a problem if it is not emptied. If a Qt window is minimized, it won't invoke a draw event, so the queue is not flushed, and it builds up.
The solution/workaround is to call `canvas.context.flush()` explicitly. There are multiple examples affected by this. Basically any example that does *any* update to a GPU buffer, texture or program. However, most these updates are so small that it does not show a noticable memory increase (no increase seen in the process manager). These two examples change so much data at such a high speed that it does matter.
@rossant here's a nasty downside of the GLIR queue :)  On the long run it could be worth …

Prevent memory surge in two examples

---

CODE_OF_CONDUCT.md
README.rst

In an effort to make VisPy a more welcoming community, I'd like to add a Code of Conduct. A code of conduct allows members of the VisPy community to know what is expected of them and of the other members of the community. It also lets everyone know what actions are taken due to violations of this code of conduct regardless of the violator's "status" in the project. That means even core developers/maintainers are subject to this CoC and its punishments (including permanent ban from the community). This CoC applies to both virtual (GitHub, gitter chat, video calls) as well as in-person events (sprints, conferences, meetings, etc).
TODO:
I will be on the mailing list. Who else is willing?

Add Code of Conduct

---

vispy/app/canvas.py
vispy/app/tests/test_canvas.py
vispy/gloo/wrappers.py
vispy/scene/canvas.py
vispy/scene/tests/test_canvas.py

This is an attempt at providing a more clear and stable way for users to get a numpy array of the current visualization. Users often see the `Canvas.render` method, but are then surprised by some of the results. For example:
https://github.com/napari/napari/issues/1566#issuecomment-690748249
I think it may be more important for us to figure out a way around this. I've made this PR to discuss it and to provide a possible workaround with a `Canvas.screenshot` method as the `_screenshot` utility function is my usual go to response for users who run into `.render` issues. @almarklein and I discussed this a little here: https://github.com/vispy/vispy/pull/2082#issuecomment-864962729
I think in the best case `.render` would produce the expected results, but I'm not sure what the proper solution …

Fix alpha handling in 'translucent' Visuals and add 'alpha' keyword argument to Canvas.render

---

vispy/scene/widgets/grid.py

Closes #2093 
Closes #2099 
Closes #2097 
This closes the issue mentioned above and replaces the PRs mentioned. While debugging #2093 I noticed that the `height` of a widget would sometimes be set to `0` randomly. I thought I remembered kiwisolver's documentation talking about how to print out information about the solver so I was looking for [that](https://kiwisolver.readthedocs.io/en/latest/basis/solver_internals.html#inspecting-the-solver-state) when I found https://kiwisolver.readthedocs.io/en/latest/basis/basic_systems.html#solving-and-updating-variables. This mentions that if you suggest a new value for a variable you also have to later run `.updateVariables()` to have the solver actually calculate the new results.
I made the changes in this PR and ran the example code in #2093 for …

Fix grid solver not updating variables when height/width changed

---

vispy/visuals/filters/mesh.py
vispy/visuals/tests/test_mesh.py

Addresses the main point in  #2087
* Make the depth step for calculating the view direction a bit smaller to avoid glitches.
* Fixes that the view direction was reversed. I don't think this caused any problems, but it did cause confusion while making changes. (I verified the direction by adding `light_vec = eye_vec`.)
* Changes the reflection model to the better Blinn-Phong: see https://learnopengl.com/Advanced-Lighting/Advanced-Lighting.
* Tweaked default light paramseters.
Dropping this here:
```
// Note (AK): Below is a way to flip the surface normal so that it's always in
// the view direction. However, this only works well when the light and view
// vector are (about) the same. Otherwise, normals on faces that that are
// near-parallel to the eye vector can flip, affecting how …
```

Improve specular light in phong shading

---

vispy/scene/tests/test_canvas.py
vispy/scene/widgets/widget.py
vispy/visuals/mesh.py

Closes #2107
See #2107 for the long debug process and discussion on this. Basically the MeshVisual used by the ViewBox (and all Widget objects) only has `cull_face` set, but depends heavily on the behavior/setting of depth testing. This PR forces depth testing to be off which seems to make this picking Mesh behave more consistently with ViewBox child Visuals.
TODO:

Fix inconsistent picking behavior regarding depth testing

---

vispy/visuals/image.py
vispy/visuals/tests/test_image.py

This PR refactors the ImageVisual's creations of its Texture object. This is to help me in my own applications where I want to subclass the ImageVisual. This simple change gives me much more control over how the textures are created while not requiring me to replicate the whole `__init__`. There is probably larger refactor that could serve subclasses (like the one @tlambert03 is working on in #1999), but I'm not sure we're ready for that yet. I hope to find some time today to use this refactor in my application and make sure it works. Eventually the subclass I'm working on will probably be added to VisPy-core.

Refactor ImageVisual for easier subclassing

---

vispy/visuals/visual.py

Closes #2109 
As discussed in #2109, this moves when the GL state is applied/sent to the GPU. This is things like depth test, blend functions, etc. Previously this was done *before* `_prepare_draw` of the individual Visual was called. If `_prepare_draw` returns `False` then a `Visual` isn't drawn and this is wasted. This PR is currently just a test to see what happens if we do this change. In the best case this passes all tests and is a slight performance improvement. In the next best case it only effects the `TextVisual` which has some complicated rendering before "real" drawing. Worst case is there are settings that reset GPU state (like clear color?) and doing these after texture, buffer, and other data commands will cause issues. In this last case, this can't be merged.

Change Visual GL state so it is only set if drawing

---

vispy/visuals/volume.py

This fixes #2114. While this does not affect anything currently, it will cause problems in the future (such as with clipping planes).

Do not refine mip/minip if nothing was found

---

vispy/app/tests/test_app.py
vispy/app/tests/test_context.py
vispy/app/tests/test_simultaneous.py
vispy/gloo/tests/test_use_gloo.py
vispy/testing/__init__.py
vispy/testing/_runners.py
vispy/testing/_testing.py
vispy/testing/image_tester.py
vispy/visuals/tests/test_arrows.py

I wanted to do an xfail in #2106 and realized that we have `os.getenv` all over the tests. I felt replacing these with constants in the testing utilities would make this simpler and cleaner in the long run.

Replace CI environment variable checks with constants

---

vispy/visuals/image.py
vispy/visuals/tests/test_image.py

This was discussed a little in #2085 and I know this current implementation isn't optimized (multiple nan checks and branches), but I wanted to start the discussion since this shows (I think) what we want the end result to be. For single channel images, the NaN pixels should be fully transparent (or discarded). For RGB images, if all pixels are NaNs then make them transparent, otherwise make them the lower clim limit.
Thoughts? Changes?

Add handling of NaNs in ImageVisual

---

.github/workflows/wheels.yml

As discussed in #2104 we should upload test packages to test PyPI. This is my attempt at getting the workflows setup for this. @kmuehlbauer how does this look?
CC @sofroniewn

Add CI job for uploading to test PyPI

---

vispy/color/colormap.py
vispy/visuals/mesh.py

This allows to get proper file/line for deprecation in test suite, which
make it a bit easier to track where the errors come from.
Also update a literal usage of get_colormap('cubehelix') with the
corresponding new import.

Set stacklevel for colormap deprecation.

---

vispy/ext/cocoapy.py

As requested by @djhoese here:
https://github.com/vispy/vispy/pull/1975#issuecomment-873084868
In order to have vispy run on Apple Silicon M1 (arm64) some functions marked as OBJC_ARM64_UNAVAILABLE need to be screen via arch
See also: 
https://github.com/pyglet/pyglet/pull/335/commits/5aa1870188b9675cdee090bbecb342661ccc06a6
This fix was originally proposed by @isuruf here:
https://github.com/vispy/vispy/issues/2013#issuecomment-819690863
And then expanded by @watjurk here:
https://github.com/vispy/vispy/issues/2013#issuecomment-819724112
However, the first two lines they also modified:
```
objc.class_getClassMethod.restype = c_void_p 
objc.class_getClassMethod.argtypes = [c_void_p, c_void_p] 
```
seem to not need skipping on M1.
Using this fix, napari (python image viewer, etc.) runs …

Fix for Apple Silicon M1 (arm64)

---

vispy/visuals/filters/color.py

This PR will allow users to pass keyword arguments to the subclassed filters in ```color.py```.
Closes #2143

Add filter keyword arguments to subclassed filters

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

Right now, updating the `cmap` property of the volume visual either doesn't change anything or results in an ugly traceback. This PR is upstreaming a fix for that from napari, originally made by @sofroniewn.
Here is an example you can play with
```python
"""
Example volume rendering
Controls:
* 1  - change colormap
"""
from itertools import cycle
from vispy import app, scene, io
from vispy.color import get_colormaps, BaseColormap
from vispy.visuals.transforms import STTransform
vol1 = np.load(io.load_data_file('volume/stent.npz'))['arr_0']
canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
view = canvas.central_widget.add_view()
volume = scene.visuals.Volume(vol1, parent=view.scene, threshold=0.225)
fov = 60.
cam1 = …
```

Fix `VolumeVisual.cmap` setter not working for most colormaps

---

vispy/visuals/volume.py

The comments in #2113 inspired this PR.
There seems to be no reason for the volume visual to be inconsistent with the rest of the visuals (apart from maybe a marginal performance improvement by pre-formatting the string). This PR replaces the pre-formatted shaders of each volumetric rendering method with vispy's `$variable` notation.
This makes fragment code clearer (no double `{{`) and makes the rendering methods work the same as any other variable in the shaders.

Migrate from string formatting to template ($) variables in VolumeVisual shaders

---

ci/requirements/linux_full_deps_pip.txt
examples/ipynb/Rotating Cube.ipynb
vispy/app/application.py
vispy/app/backends/__init__.py
vispy/app/backends/_ipynb_rfb.py
vispy/app/backends/_jupyter_rfb.py
vispy/app/backends/_offscreen_util.py
vispy/app/backends/tests/test_offscreen_util.py
vispy/app/backends/tests/test_rfb.py
vispy/app/base.py
vispy/app/canvas.py
vispy/gloo/glir.py
vispy/plot/tests/test_plot.py
vispy/scene/canvas.py

This implements a new backend based on `jupyter_rfb`. I'll be updating jupyter_rfb at the same time, so it aint easy to give this is a spin yet. This is basically the same as what was intended with the `ipynb_vnc` backend, but all the "hard parts" are delegated to an external library.
Includes a new simple way to create a (global) hidden window just for having a GL context, plus an approach to render offscreen using an FBO. The event system integrates with asyncio, because that's what Jupyter uses (via Tornado).
Closes #2127, closes #134, relates to all issues tagged with the jupyter-widget tag.
Todo:

Jupyter widget based on jupyter_rfb

---

.github/workflows/wheels.yml

Addresses the build issues identified and discussed in #2116 
Currently cibuildwheel is trying to build with Python 3.10. However, many libraries don't have wheels for 3.10 yet (including vispy) and this causes issues for CI. We depend on Pillow for testing our wheels and since Pillow doesn't currently have a 3.10 wheel it tries to build from source during cibuildwheel's test phase. This fails with some missing C dependencies.
This PR switches to using the new PyPA-based cibuildwheel github action and skips testing the wheel for Python 3.10.

Switch to cibuildwheel github action and skip 3.10 wheel building

---

examples/basics/scene/volume_clipping.py
examples/scene/volume_clipping.py
vispy/visuals/volume.py

After trying to implement this [in napari](https://github.com/napari/napari/pull/2934) and getting some very useful input in #2113, here's a pure vispy implementation of clipping planes for the Volume visual.
I added an example (`examples/basics/scene/volume_clipping.py`) with some simple keybindings to showcase the code (thanks @alisterburt for your code at #2074 :)).
https://user-images.githubusercontent.com/23482191/123859348-d1646600-d924-11eb-8c12-d28f9fe087a9.mp4
Planes are defined as two vec3 (position and normal vector), and are used to clip the volume (anything on the negative side of the normal vector is not shown). The shape of `volume.clipping_planes` should therefore be `(n_planes, 2, 3)`.
Currently, the vector coordinates are normalized in (0, 1), but they should probably be …

Add clipping planes to `VolumeVisual`

---

examples/scene/volume_clipping.py

First of all, thanks for an amazing project!
Pressing a modifier (e.g., shift) in the `examples/scene/volume_clipping.py` example caused an error (traceback below) since `''in 'xyzo'` evaluates to `True` [here](https://github.com/vispy/vispy/blob/3ef02c5f1ae6bf34616060e350d7e1818c8d3c21/examples/scene/volume_clipping.py#L117). I have added a small check in `add_clip()` to make sure `mode` is valid before attempting to add a clipping plane.
edit: I also removed some lines of code that seemed unused.
```python
WARNING: Traceback (most recent call last):
File "/Users/kyamauch/Documents/vispy/examples/scene/volume_clipping.py", line 130, in <module>
app.run()
File "/Users/kyamauch/Documents/vispy/vispy/app/_default_app.py", line 60, in run
return default_app.run()
File …
```

Fix minor bug in volume_clipping.py example

---

vispy/util/ptime.py

since '3.10' is smaller than '3.3', sys.version < '3.3' returns True for python 3.10

Fix python version check for python > 3.9

---

vispy/app/backends/_tk.py

character keys (letters/digits) are not properly detected by the tkinter backend.
Somehow, the keycode value is not the same as the ordinal of a character in tkinter.
My changes fix this by looking at the 'char' field of the event.

Fix key event handling in Tk backend

---

vispy/visuals/markers.py

A new marker in MarkersVisual that looks like a 'skinny' version of the already existing 'cross' marker.
The red cross is an example of this marker:

Add skinny cross marker (++) to MarkersVisual

---

examples/scene/marker_spheres.py
examples/scene/point_cloud.py
vispy/visuals/graphs/graph.py
vispy/visuals/markers.py

Turns out getting #2204 into the `Markers` visual was doable. This is an alternative implementation of that PR: ~instead of creating a new visual, I used the infrastructure of `Markers` and added another symbol called `sphere`. In pratice, this symbol uses the same cropping function as `disc`, but adds all the lighting stuff that #2204 introduced.~
This implements a `spherical` attribute in the `MarkersVisual` that add a sphere-like shading to the markers. It's applicable to all the symbols, but particularly useful with `disc`, because it results in depth-correct spheres.
Due to the significant changes to the shaders, this PR would in practice also supersede #2198.
This is the render from the added example:
https://user-images.githubusercontent.com/23482191/133228329-f1bc3482-dac5-40a7-ac3 …

Spherical (3D-looking) `Markers` symbols

---

examples/scene/clipping_planes.py
examples/scene/volume_clipping.py
vispy/gloo/__init__.py
vispy/visuals/filters/clipping_planes.py
vispy/visuals/volume.py

Following suggestions in #2176 and #2177, I'm attempting to use filters for the same application.
~Things *seem* to work, but I get weird visual artifacts. I'm not sure how to debug them, and I would like some suggestions.~
EDIT: this now works as intended! See https://github.com/napari/napari/pull/3252 for a cool application :) Tested and worked with:
- lines
- markers
- meshes
https://user-images.githubusercontent.com/23482191/131091370-c673a384-ec49-4158-9b8f-96a7618349f7.mp4
Try out this code in ipython:
```python
from vispy.visuals.filters.clipping_planes import PlanesClipper
clip = PlanesClipper()
clip.clipping_planes = np.array([[[0, 0, 0], [0, 0, 1]], [[0, 0, 0], [0, 1, 0]]])
%run examples/scene/mesh_shading.py
mesh.attach(clip)
```

Add PlanesClipper filter for visually clipping visuals by a 2D plane

---

vispy/gloo/texture.py
vispy/visuals/cube.py
vispy/visuals/markers.py

That give the correct location most of the time for where the fix/update
should be instead of pointing into vispy codebase.
That make updates by consumer easier (and thus more likely),
And in turn should make you more confident about removing deprecated
things.

Use stacklevel in DeprecationWarnings.

---

.github/workflows/main.yml
ci/requirements/linux_osmesa_deps_conda.txt
vispy/visuals/_scalable_textures.py
vispy/visuals/image.py
vispy/visuals/tests/test_image.py

fixes #2229.
looks like the `if not new_if and new_cl and not self._need_colortransform_update:` conditional in the current `_build_texture` method is a little too strict.   Back in https://github.com/vispy/vispy/pull/1911, we fully updated the color transform whenever the image texture was rebuilt.  #1920 tried to make that a little more performant, by only updating when necessary, but it looks like the heuristic isn't perfect.  This is somewhere in the middle, only rebuilding the color transform when the internal format has changed, otherwise updating the texture clims stored in the color transform (which have likely changed during the `scale_and_set_data` call)
with the time available, I wasn't able to determine a better way to _know_ for certain whether those texture clims have …

Update clims in color transform whenever texture._data_limits changes

---

doc/installation.rst
vispy/geometry/meshdata.py
vispy/visuals/filters/mesh.py
vispy/visuals/filters/tests/__init__.py
vispy/visuals/filters/tests/test_wireframe_filter.py
vispy/visuals/mesh_normals.py
vispy/visuals/tests/test_mesh_normals.py

When MeshNormal is provided an empty `MeshData` object, all sorts of issues arise, crashing the program. This is especially problematic if one wants to automatically update a `MeshNormals` based on a `Mesh`, which is totally fine with empty data.
I tried fixing this by making the methods in `MeshData` used by `MeshNormals` (such as `get_vertex_normals`) more resilient, but I encountered all sorts of issues. The most straight forward way to solve it ended up being this.
As an added bonus, this PR allows to use `set_data` to update properties of the `MeshNormals` object which are not accounted for by the `LineVisual` (for example, `length`).
~It's missing some tests, but it should be funcional.~
EDT: I added a similar check for `WireframeFilter`, which was failing when `_update_data` was …

Fix MeshNormals and WireframeFilter with empty MeshData

---

vispy/scene/visuals.py

small change that makes it much easier to work with vispy classes in an IDE.
currently, since `create_visual_node` dynamically creates a type, you pretty much lose all type hinting and autocompletion in an IDE when working with visual nodes. 
With this change, you at least retain the methods and constructor on the corresponding Visual, (though, due to the dynamic type creation, it's still not possible to retain the merged attributes of both the `VisualNode` and the underlying `Visual`).

Add typing to `create_visual_node`

---

vispy/app/backends/_glfw.py

the encoding is already done in glfw.set_window_title through a call to _to_char_p (at least since glfw 2.3.0 )

remove utf-8 encode in _vispy_set_title

---

.github/workflows/main.yml
doc/conf.py
doc/installation.rst
examples/gloo/geometry_shader.py
vispy/geometry/triangulation.py

This adds documentation on the usage of `Triangle`/`triangle` as discussed in #1029.
Here are some findings I made:
- triangle is only used in class https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/vispy/visuals/collections/raw_polygon_collection.py#L13
- unfortunately tiger-demo (https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/examples/collections/tiger.py) segfaults with triangle
- The speedup for https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/examples/collections/polygon_collection.py is 97% (472ms internal Python implementation, 13ms triangle).
closes: #1029

MNT: add documentation of usage of Triangle/triangle, see #1029

---

vispy/visuals/markers.py
vispy/visuals/tests/test_markers.py

When passing an array to `Markers.edge_width`, a `ValueError` is raised:
```python
if edge_width < 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
This PR fixes this by using `np.all`.
Also, if a `list` is passed, the comparison fails because
```python
TypeError: '<' not supported between instances of 'list' and 'int'
```
Therefore, I added a line to cast to array first.

Fix numpy error with array edge_width in Markers

---

vispy/app/backends/_qt.py

The touchPoints() method is replaced by points() in the Qt6 framework. The pos() and lastPos() methods are replaced in Qt6 by position() and lastPosition().
Pyside6 only mention the deprecation of the pos() and lastPos() methods but PyQt6 does not have them at all.

Fix touch event handling issue for Qt6-based backends

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This PR adds a few lines to set the depth buffer when rendering a volume with the `plane` raycasting mode.
Before/after:
https://user-images.githubusercontent.com/23482191/151813078-d36ce3a3-8d38-4eef-95ae-19709a42c16e.mp4
https://user-images.githubusercontent.com/23482191/151813074-80e989d9-ee5d-4847-bf24-818bb2d8d07d.mp4

Set depth buffer in Volume plane rendering

---

.github/workflows/wheels.yml

Added linux aarch64 wheel build support.
Related to https://github.com/vispy/vispy/issues/2277, @djhoese Could you please review this PR?

Add Linux AArch64 wheel build support

---

vispy/app/backends/_qt.py

KeyboardModifiers follows from C++ QFlags<> which is closer to set-like semantics,
even if its implementation may be a bit field. Swapping to `qtmod & q` lets it
perform properly as a result.
This was triggering in SIFT 1.2.3 on mouseMove events as
```
TypeError: unsupported operand type(s) for &: 'KeyboardModifier' and 'KeyboardModifiers'
```
Also a minor comment fix to a presumed-missing "Compat" comment since it follows from nearby kin.
Closes #2212

Fix TypeError for membership test of KeyboardModifiers

---

doc/conf.py
vispy/io/stl.py
vispy/scene/node.py

Closes #2295. Realized today that the website generation CI job is failing. Seems to be related to an update in some dependency, likely numpydoc. This PR fixes a few of the complains from numpydoc as well as updates the intersphinx URLs to scipy and numpy. I'm a little worried because the scipy URL says "devdocs" in it which may not be the final/stable version of the documentation. We'll see...

Fix sphinx generation for new versions of numpydoc

---

examples/basics/visuals/line_draw.py

Moved line 96 into the Canvas class (on_mouse_press method) so it can now see the event object.
The next line
would also fail in uncommented but as it changes the pos_scene variable it is not so straightforward to fix unless event is also sent to the method, changing the API.

moved a debug line to where it works

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This PR sets the depth buffer correctly in the `mip`/`minip`/`attenuated_mip` rendering modes of the `VolumeVisual` - if in plane rendering mode the depth is always set to the ray-plane intersection as before (#2289)
https://user-images.githubusercontent.com/7307488/156226184-e0146fd2-a0af-4e02-8148-1aa8c6af5200.mp4
This allows us to compose multiple volumes in the same space in opaque blending modes (excuse the lack of alpha in the cmap)
https://user-images.githubusercontent.com/7307488/156226373-7dbd943d-5be9-4dd1-b5e8-23927e6e6e64.mp4
cc @brisvag

Set depth in `VolumeVisual` for `mip`/`minip`/`attenuated_mip` rendering modes

---

vispy/visuals/tests/test_volume.py
vispy/visuals/volume.py

This PR takes out some code from the solution to the issues in #2305.
Specifically, see [this comment](https://github.com/vispy/vispy/pull/2305#issuecomment-1059240483) and [this other comment](https://github.com/vispy/vispy/pull/2305#issuecomment-1059272289).
In practice, the new attributes allow to set a lower bound to MIP projection (and higher bound to MINIP) beyond which fragments are discarded.

Add cutoff to mip and minip volume projection for fragment discard

---

vispy/geometry/rect.py
vispy/scene/cameras/panzoom.py

from @jni and myself - here is a fix for napari/napari#3723, we added a center setter to the `Rect` class and use this rather than specific logic in the panzoom camera center setter.
The logic in the previous setter was incorrectly setting the rectangle coordinates to the delta between centers, rather than shifting by that delta.

Fix panzoom camera center setter

---

vispy/scene/cameras/panzoom.py

This adds a reference to the ways the view rectangle can be specified, clearing up potential confusion. Fixes https://github.com/vispy/vispy/issues/2316.

Expand docs on panzoom rect setter

---

examples/scene/nested_viewbox.py

Changed "Nexted Viewboxes" --> "Nested Viewboxes" 
This leads to more serious typos in user generated docs ( see: https://vispy.org/gallery/scene/nested_viewbox.html title and label in right pane)

Fixed Typo in Nested Viewbox Name

---

vispy/visuals/line/line.py

numpy.ascontiguousarray should not make copies unnecessarily, see https://stackoverflow.com/a/51457275 for example. [astype](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html#numpy-ndarray-astype) will make copies by default.

Reduce memory copies in LineVisual

---

examples/scene/clipping_planes.py
vispy/visuals/filters/clipping_planes.py
vispy/visuals/volume.py

In napari/napari#4503, @ch-n noticed something wrong with the behaviour of clipping planes and the `Volume` visual. This PR fixes that issue.
EDIT: I added changes to the example for testing, but those should probably be reverted before merging!
Specifically, the problem was introduced with #2197, where the ability of using any coordinate space for clipping planes was added, and I messed up the math :P We need to convert the texture coordinate to the chosen space *after* reshaping, and then clip by simply comparing the pure clip coordinates with the new location. Instead, I was doing a weird messy mix that only worked because all the tests were with a non-transformed volume. Once again, I'm getting burned by non-generalized testing :/
Additionally, this PR changes …

Fix clipping planes logic for `Volume` and `PlanesClipper`

---

.github/workflows/wheels.yml

cibuildwheel no longer recognizes python version specifiers older than Python 3.6. This means we no longer need to skip Python 2.7, 3.4, and 3.5. In fact, cibuildwheel was failing because we were specifying them. Let's see how this CI goes...

Fix cibuildwheel failing on skipping old python versions

---

README.rst

The README.rst is using .md syntax for the link to the CHANGELOG.md.
This fixes it to use .rst syntax, so the link works.

Fix link to CHANGELOG.md in README.rst

---

vispy/app/tests/test_canvas.py
vispy/gloo/wrappers.py
vispy/scene/tests/test_canvas.py

In https://github.com/vispy/vispy/pull/2320 new `blend_equation` options were added. 🎉 
But existing presets (`GL_PRESETS`) don't explicitly set `func_add` as the `blend_equation`—it is the default though. Meanwhile, `set_state` essentially toggles functionality (`glBlendEquation` in this case), so if a different `blend_equation` is explicitly specified and then a preset is used currently, the blend equation is re-used for the preset, because the preset does not re-enable the default. 
I think this behavior is unintuitive and should be considered a bug.
This PR explicitly sets `blend_equation='func_add'` in the `translucent` and `additive` GL_PRESETS so use of the preset alone always sets the correct `blend_equation`. The user can still override, as usual.
Try this from the examples:
``` …
```

Add `blend_equation` (add) to GL_PRESETS

---

.github/workflows/main.yml

Small change attempting to fix the testing workflow on the examples run, which currently fails with a bunch of:
```
WARNING: QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/tmp/runtime-runner', please create it with 0700 permissions.
```
I don't know why this showed up now, maybe some newer version of Qt is not automatically creating this, while it used to?

Fix test examples on CI

---

doc/installation.rst
examples/gloo/animate_shape.py
vispy/io/image.py
vispy/util/wrappers.py
vispy/visuals/collections/array_list.py
vispy/visuals/collections/base_collection.py
vispy/visuals/visual.py

There are small typos in:
- doc/installation.rst
- examples/gloo/animate_shape.py
- vispy/io/image.py
- vispy/util/wrappers.py
- vispy/visuals/collections/array_list.py
- vispy/visuals/collections/base_collection.py
- vispy/visuals/visual.py
Fixes:
- Should read `successive` rather than `succesive`.
- Should read `arguments` rather than `argments`.
- Should read `vertices` rather than `vetices`.
- Should read `specific` rather than `specifc`.
- Should read `specialized` rather than `speacialized`.
- Should read `separate` rather than `seperate`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

Fix a few comment and docstring typos

---

examples/basics/visuals/rescalingmarkers.py
examples/scene/point_cloud.py
vispy/visuals/graphs/graph.py
vispy/visuals/markers.py

This PR allows to provide `symbol` on a per-point basis in a `Markers` visual.
Currently, the single `symbol` attribute forces users to create multiple visuals if they want multiple symbols; instead, we can accept an array of symbols and handle everything in the shader. I changed the example `point_cloud.py` to take advantage of this, and everything seems to be working great!
Since we cannot pass enums/strings/integers to the shader, we're forced to convert to float and do some gymnastic to get everything to work, which makes things a bit less readable. One downside of this is that `Marker._data['a_symbol']` will contain a bunch of uninterpretable floats, but since this is a private attribute it shouldn't be a big deal.

`Markers`: allow setting `symbol` on individual basis

---

.github/workflows/wheels.yml

CI is often skipping/failing the macOS wheel workflow; turns out, we're using a deprecated runner. This updates to the recommended one: https://github.com/actions/virtual-environments/issues/5583.

Switch to newer macOS ci

---

vispy/visuals/markers.py

Fix for #2357. The solution was to use `scene` coordinates rather than `visual` coordinates for the calculation, so we do everything in a space where the scaling already happened.
~While this fixes the size of the markers, edge width is probably affected too since it uses pure `a_size`... I need to investigate that.~ EDIT: this works just fine!
To test this out, try the following here versus `main`:
```py
canvas = scene.SceneCanvas(show=True)
view = canvas.central_widget.add_view()
view.camera = scene.cameras.ArcballCamera(fov=0)
points = scene.visuals.Markers(
pos=np.array([[0, 0, 0], [0.2, 0.1, 0.3]]),
size=0.1,
edge_width=0.01,
edge_color='red',
scaling=True,
parent=view.scene,
)
points.transform = scene.transforms.STTransform(scale=(5, 2, 1)) …
```

Fix marker size with anisotropic scaling

---

vispy/visuals/tube.py

Fix reference to Iterable abstract base class (abc).  It has been moved to collections.abc and removed from collections in Python 3.10.

Update tube.py to support Python 3.10 and higher.

---

vispy/gloo/program.py
vispy/gloo/tests/test_program.py

Real fix for the issue found at #2377.
Currently, we were treating `in` and `attribute` *exactly* the same, even when parsing: we were looking for the token `attribute` when parsing in both cases, effectively doing the same thing twice.
What we really should be doing is look for the `in` token, but treat it the same as attribute.
There are still limits with this approach (`in` can actually be a either `attribute` or `varying` depending on if it's used in a vertex or fragment shader), but it's out of scope for this pr.

Use correct regex when parsing variables

---

vispy/app/backends/_wx.py

As mentioned in #2395 the wx backend had a bug with the wx timer receiving a float as argument, instead of an integer

fix: wx timer from float to int

---

README.rst
ci/requirements/linux_full_newqtdeps_pip.txt

As discussed in our last monthly meeting, the governance documents are a little difficult for newcomers to find. This PR adds this information to the README. In the last meeting @rougier, @larsoner, and others brought up that github may have a specific document names that it looks for in the root of the repository and links to. From what I can tell there is nothing like this for GOVERNANCE documents (code of conduct and contributing documents are different). Because of this I have decided not to include any softlinks or "stub" files with specific names in the root of the repository.
Side note: @brisvag I've included in this a patch to force the PyQt6 version in the CI test environment so hopefully our Qt6 tests pass again and don't seg fault.

Add governance and steering committee information to README

---

examples/scene/image_custom_kernel.py
vispy/visuals/image.py
vispy/visuals/tests/test_image.py

When trying to expose in napari the custom interpolation kernels from #2319, I found some issues:
- due to the automatic normalization, the shader was really only suitable to gaussian blurring or other filters where total intensity should be preserved. This is especially bad with kernels with negative values
- after fixing the above, negative values still didn't work. It turns out that we need to specify the internalformat so it actually uses floats and allows negative numbers (If I understood correctly).
These changes fix the above, but do not guarantee normalized kernels anymore, so users have to do it themselves. I updated the example to do this, and made it a bit better at showcasing what this can do.

Fix custom image interpolation kernels to work with negative numbers

---

vispy/visuals/filters/clipping_planes.py

Over at napari we noticed that with some specific GPUs (Intel Iris so far), we gat very bad performance when recompiling programs, due to these lines:
https://github.com/vispy/vispy/blob/16d8c5bd8694df9c18086e6fad31ffbaa08abaf4/vispy/visuals/filters/clipping_planes.py#L103-L114
In `0.10`, the `Function` was cached, which turned out to be problematic when working with multiple instances of the filter (due to [this issue](https://rednafi.github.io/reflections/dont-wrap-instance-methods-with-functoolslru_cache-decorator-in-python.html).
However, now a new `Function` gets create every time, even when unnecessary. Granted, in napari we are mistakenly calling this setter *way* too often, which we are fixing, but this should probably be checked in vispy as well.

clipping planes performance: do not create a new function willy nilly

---

vispy/app/backends/_qt.py
vispy/app/tests/test_context.py

Fixes #2407 by using `SwapBehavior` to set DoubleBuffer
PYSIDE6_API is included in the existing PYQT6_API logic:
https://github.com/vispy/vispy/blob/8bf4f9e538dee5cb986779006b84f62eed81ed7c/vispy/app/backends/_qt.py#L281-L287
This should work for PySide6 going back to at least 6.2 (LTS)
I found the Qt 6.2 (LTS) docs. The swap behavior was already present.
https://doc.qt.io/qt-6.2/qsurfaceformat.html#SwapBehavior-enum
https://doc.qt.io/qtforpython-6.2/PySide6/QtGui/QSurfaceFormat.html#PySide6.QtGui.PySide6.QtGui.QSurfaceFormat.SwapBehavior
Edit: Also uses the same BUTTONMAP as PyQT6
Plus, xfails the shared context tests: test_context.py
Fixes https://github.com/vispy/vispy/issues/2410

Improve PySide6 Support: swapBehavior for DoubleBuffer, BUTTONMAP as pyqt6, xfail test_context

---

vispy/scene/cameras/base_camera.py
vispy/scene/cameras/turntable.py

This is the same as #2393. I was unable to recover the commits with cherry-pick, because there were multiple copies of the same commits with slightly different contents and with the wrong authors. Hopefully this was all the changes we wanted from that?
cc @djhoese

Allow 180 fov and clarify docstring

---

vispy/visuals/volume.py

This is a change I proposed in https://github.com/napari/napari/pull/5215, where it was suggested to fix upstream.
This changes the `attenuated_mip` shader to scale values when calculating the attenuation. I think this is only relevant for certain data types and configurations where the `texture_format` is not normalized. It has two effects:
* The attenuation factor is more consistent across data values, which should require less "tuning" for specific datasets.
* If the image has negative values they pretty much break the current algorithm and amplify instead of attenuate values.
Here is a comparison without (left) and with (right) this change demonstrating the degenerate results when the texture has negative values:

Scale values when calculating attenuation in attenuated_mip shader

---

.github/workflows/main.yml
ci/requirements/linux_full_deps_conda.txt
ci/requirements/linux_full_newqtdeps_conda.txt
ci/requirements/py310.yml
ci/requirements/py38.yml

As discussed in the monthly meeting, we're switching to newer python for CI. I'm not sure how the workflows work, so this is likely to be completely wrong as a first attempt :P

switch to newer python for ci

---

vispy/visuals/markers.py
vispy/visuals/tests/test_markers.py

Another lesson on why having tests is good. Due to the latest changes to `Markers.symbol`, both setter and getter were failing when called on Markers with empty data, because they both assumed that `self._data` was not `None`.
This PR is a bugfix for both cases, and adds a small test which failed on main. Note that the test also triggered the `getter`, because `frozen` uses `hasattr`, which in turns [uses `getattr` under the hood](https://docs.python.org/2/library/functions.html#hasattr). This is actually how I noticed the error in the first place...
This should probably go in a patch release asap.

Fix: bug with new Markers.symbol and empty data

---

examples/plotting/colorbar.py
vispy/color/color_array.py
vispy/visuals/tube.py

This fixes the issue first seen in #2438. The error seen was:
```
>       assert_array_equal(rgb, ColorArray(np.eye(3)))
vispy/color/tests/test_color.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = (<built-in function eq>, <ColorArray: 3 colors ((1.0, 0.0, 0.0, 1.0) ... (0.0, 0.0, 1.0, 1.0))>, <ColorArray: 3 colors ((1.0, 0.0, 0.0, 1.0) ... (0.0, 0.0, 1.0, 1.0))>)
kwds = {'err_msg': '', 'header': 'Arrays are not equal', 'strict': False, 'verbose': True}
@wraps(func)
def inner(*args, **kwds):
with self._recreate_cm():
>           return func(*args, **kwds)
E           ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.
```
Now when I started debugging this I got into …

Fix ColorArray failing with numpy 1.24.0

---

vispy/geometry/meshdata.py
vispy/geometry/tests/test_meshdata.py

Suggestion to extend https://github.com/vispy/vispy/pull/2433 with tests, clarification of documentation and some formatting.

Vectorize MeshData vertex normals computation

---

vispy/geometry/meshdata.py
vispy/geometry/tests/test_meshdata.py

Supersedes #2098.
Summary:
- Test computation of face normals.
- Extract computation of face normals and vertex normals out of MeshData for clarity.

Clean up and test computation of normals in MeshData

---

vispy/gloo/program.py

I just noticed this small issue while working on something else, the missing `f` causes the error to be missing the intended debug info.

Fix f-string missing prefix in gloo/program.py error message

---

vispy/color/color_array.py

The `_string_to_rgb` helper function uses `color.lower()` to raise a ValueError, because the names are all lower case in `_color_dict`. However, in the next line, it still uses `color` as the key to the dict, which means that if the string is upper case, the first logic passes, but then a KeyError happens. This was first reported here in napari: 
https://github.com/napari/napari/issues/5599#issuecomment-1455280966
So this PR simply makes sure to use `color.lower()` as the key to the `_color_dict` dictionary.
All tests pass for me locally with this and the napari issue is fixed.

Bugfix: Use color.lower() for _color_dict keys

---

vispy/visuals/mesh.py
vispy/visuals/tests/test_mesh.py

Rendering a mesh with `vertex_values` produces a shader compilation error when `mesh.clim == "auto"` (the default):
```
RuntimeError: Shader compilation error in GL_VERTEX_SHADER:
on line 336: Use of undeclared identifier 'a'
float cmap(float val) { return (val - a) / (u - a); }
on line 336: Use of undeclared identifier 'u'
float cmap(float val) { return (val - a) / (u - a); }
on line 336: Use of undeclared identifier 'a'
float cmap(float val) { return (val - a) / (u - a); }
```
These "undeclared identifiers"  `a` and `u` are meant to be numbers that come from `mesh.clim`, but this attribute may be a tuple or the string `"auto"`, so here it was taking the first two characters from that string instead of the values.

Fix shader compilation error for MeshVisual when mesh.clim = 'auto'

---

.github/workflows/wheels.yml

At present vispy doesn't have wheels for arm64 macOS.
It builds from source just fine, but not everyone may have development tools.
Wheels make things potentially safer and of course faster.
In this PR I add use of `CIBW_ARCHS_MACOS` to the existing workflow, setting 'x86_64 arm64'. This results in wheels cross compiled for arm64 in addition to the x86 ones. The runners are x86, so the arm64 wheels won't be tested.
I tested this on my fork (see https://github.com/psobolewskiPhD/vispy/actions/runs/4589168480?pr=1 but note I messed up tags, so only the macOS ones have proper version), downloaded and I installed the 3.10 and 3.11 wheels locally on my arm64 mac and everything works same a with build-from-source (`pip install .`). 
```
===== 18 failed, 768 passed, 132 skipped, 5 xfailed, 60 …
```

[Maint, CI] Build arm64 macOS wheels via CIBW_ARCHS_MACOS

---

examples/basics/visuals/markers.py
vispy/visuals/markers.py

Closes #2453. Related #2359.
As discussed in #2453, this restores the default behavior of the `MarkersVisual` before #2359 was merged. It switches the boolean `scaling` keyword argument to a string option of "fixed" (same as False), "scene" (same as True), or "visual" (same as True from #2453). Although we wish things could be simpler, easier, and clearer, this may be the least amount of work to restoring prior behavior while at least giving users access to the fixes from @brisvag in #2359.
CC @arcanerr @ameraner

Switch MarkersVisual scaling option to string "fixed", "scene", or "visual"

---

examples/scene/instanced_mesh.py

A surprisingly simple visual for arbitrarily oriented and colored meshes using instanced rendering.
I started on this as a way to have "true 3D" markers for solving #2453, but adding arbitrary orientations turned out to be relatively easy, and that's useful fo r stuff I'm working on :P
Basically, replace the mesh with a simple [icosphere](https://github.com/vedranaa/icosphere/) and you get your real pysically sized markers that work in both 2D and 3D. Notice how I applied a scaling transform to the visual in the examples, and the dinosaurs are being stretched correctly.
https://user-images.githubusercontent.com/23482191/224005681-3297902e-fd78-4fdf-a782-a14dac41d936.mp4
One thing that's missing (and likely hard to do) compared to the markers is the edge. As far as I know, the only 2 …

Instanced mesh example

---

vispy/visuals/volume.py

This idea originated from a [thread on image.sc about poor framerates for volume rendering](https://forum.image.sc/t/poor-3d-viewer-performance-in-napari/68103) napari. The idea is to exit the main raycasting loop early if there is no chance of finding a higher value based on the provided contrast limits. I believe this will not affect the final appearance at all and is only a performance optimization (and my testing supports this).
I don't have a realistic dataset where this makes a truly meaningful difference, but for now you can try this example (adapted from `examples/scene/volume.py`) with a huge cube of random data with/without this change and the performance difference should be apparent.
```python
from vispy import app, scene
canvas = …
```

Add early-termination optimization to attenuated mip

---

vispy/app/backends/_qt.py
vispy/scene/cameras/base_camera.py
vispy/scene/cameras/panzoom.py
vispy/scene/cameras/perspective.py
vispy/scene/cameras/tests/test_cameras.py
vispy/scene/cameras/tests/test_perspective.py
vispy/scene/canvas.py
vispy/scene/events.py
vispy/scene/node.py

This refactors the touch input to use `QNtaiveEventGesture` instead of `WA_AcceptTouchEvents` and `PinchGesture` for touchpad gesture input, as proposed in #2455. This is basically proof-of-concept and there are a number of TODOs within the code for discussion, hence the draft status. I have tested on macOS with PyQt5 and PyQt6, but would like to test other backends to make sure there are no regressions. The previous implementation was limited to macOS, but it would be interesting to try this version on other platforms. I believe Qt (6?) now has _some_ support for these gestures in Windows and Linux (Wayland).
Right now this also basically re-implements #1980 and then some, but this is mostly for testing (another reason for draft status here). For the main refactor you can just look at …

Use QNativeEventGesture for touchpad gesture input

---

vispy/app/backends/_qt.py

Sorry - some additional manual testing today revealed this bug. It seems to only be a problem with specific backend versions - the function is overloaded in Qt6 to accept either type.
Here's the error I get:
```
File ~/src/vispy/vispy/app/backends/_qt.py:568, in QtBaseCanvasBackend._handle_native_gesture_event(self=<vispy.app.backends._qt.CanvasBackendDesktop object>, ev=<PyQt5.QtGui.QNativeGestureEvent object>)
564 # this is a workaround for what looks like a Qt bug where
565 # QNativeGestureEvent gives the wrong local position.
566 # See: https://bugreports.qt.io/browse/QTBUG-59595
567 try:
--> 568     pos = self.mapFromGlobal(ev.globalPosition())
self = <vispy.app.backends._qt.CanvasBackendDesktop object at 0x293ec3760>
ev = <PyQt5.QtGui.QNativeGestureEvent object at 0x293f22a70> …
```

Fix TypeError with pinch-to-zoom

---

vispy/visuals/filters/mesh.py

While working with complex surfaces, I noticed that the shading in some cases is wierd. Turns out, the current shader is giving opposite shading depending on which side the face normals are facing. It seems that a flipping check was impplemented, but an `else` was forgotten. Check out the code below:
```python
from vispy.geometry import create_sphere
c = scene.SceneCanvas(show=True)
v = c.central_widget.add_view()
v.camera = 'arcball'
s = create_sphere(method='ico', subdivisions=5)
vert = s.get_vertices()
faces = s.get_faces()
top_left = scene.visuals.Mesh(vertices=vert + (-1, 0, +1), faces=faces[:, ::-1], shading='flat', parent=v.scene)
top_right = scene.visuals.Mesh(vertices=vert + (+1, 0, +1), faces=faces, shading='flat', parent=v.scene)
bot_left = …
```

Fix mesh shading with flipped normals

---

vispy/gloo/texture.py
vispy/scene/canvas.py
vispy/scene/node.py
vispy/scene/tests/test_canvas.py
vispy/scene/tests/test_visuals.py
vispy/scene/visuals.py
vispy/visuals/visual.py

Fixes #2501 
This is a proposed solution to the bug identified in #2501. Hopefully it's pretty self-explanatory but basically it allows you to update and restore gl state on a visual.
The only use right now is in picking, which is used in processing mouse events via `SceneCanvas.visuals_at`.

Add push/pop gl_state for visuals (used in picking)

---

vispy/visuals/markers.py

When we introduced the new `visual` scaling for markers in #2359 (later tweaked in #2470), we forgot to do the same changes in the depth buffer calculation. This lead to a mismatch between depth size and actual size. See this example in napari where with high scaling we end up with sphere that "merge" when overlapping, rather than simply obscuring each other as they should:
https://github.com/vispy/vispy/assets/23482191/24d33939-6775-4eed-94c9-507c25ef0b1b
This PR makes sure everything is calculated the same way. To avoid having many if/else and making it easier to maintain, I also moved the logic for choosing the scaling "mode" to outside the shader.

Fix spherical markers depth buffer with scaling='visual'

---

vispy/visuals/line/dash_atlas.py

This one is perhaps a bit silly, but this is a somewhat expensive operation (~70 ms on my machine) and it runs every time a `DashAtlas` is created, which is every time an `_AggLineVisual` is created. I don't think this is generally meaningful, but caching this saves a significant amount of time in the napari test suite.
I moved the function out of the class as caching a method can have undesired effects on garbage collection. The diff is a bit confusing but the code is otherwise unchanged.
It's also worth noting that `caps` appears to be unused. I am happy to remove it but don't want to break the API if anyone uses this directly (the whole method could be remove otherwise).
It's possible there is room for this code to be optimized (vectorized) in general, but I did not look into that.

Cache make_pattern on DashAtlas

---

.git_archival.txt
pyproject.toml
setup.py
vispy/visuals/text/_sdf_cpu.pyx

Closes #2522 
As talked about in the monthly meeting today, Cython 3.0 is out and we should switch to it for building or at least prepare to use it. This PR makes the full switch and only allows Cython 3+ for building. I checked the HTML output of `cython -a` for the one cython module we have (the CPU text rendering) and was able to remove a couple of low-performance spots by declaring functions as `noexcept nogil`. The `nogil` doesn't actually mean the GIL is released but since this code is happening in the GUI thread inside the TextVisual I'm not sure there is a good reason to do it any other way. There are other optimizations that could be done in the future (most likely), but I'm not sure it is worth it at this point.
I've also switch the license to an SPDX license identifier. I'll …

Update to Cython 3.0

---

examples/demo/scene/picking.py
vispy/color/colormap.py

* No longer allow *args or **kwargs to be passed in.  They have been deprecated since v0.7.
* Remove `DeprecationWarning` for several colormaps, which were all fully supported since 7d1f5966db90836ecbb003c1325d028fec7b2f4b.
Closes #2518.

Remove deprecated code from vispy.color.get_colormap

---

pyproject.toml

In #2515, the use of `oldest-supported-numpy` was replaced with the following lines in `pyproject.toml`:
```
'numpy; python_full_version<"3.12.0rc1"',
'numpy>=1.26.0rc1; python_full_version>="3.12.0rc1"',
```
Unfortunately, this broke our `min_req` tests in `napari`, because of a few reasons:
- vispy depends on just `numpy` (which means old numpy versions are supported)
- the new build constraints end up using a newer numpy version for compilation
- python3.8 (used in our `min_req` test and officially supported by vispy) no longer works with numpy>=1.25 (python>=3.9 only), which is used for compilation
As far as we (cc @Czaki) can tell, there is no reason to *not* use `oldest-supported-numpy` as dependency, for now; also, the second line in the above snippet is no longer needed, since …

return to oldest supported numpy

---

vispy/gloo/glir.py

I was playing around with sampling texels and these were required in my fragment shader.

Add ivec2, ivec3, ivec4 to ATYPEINFO in glir.py

---

vispy/visuals/ellipse.py

It was only possible to parse in the parameters as list or tuple. It is useful to accept numpy arrays

Radius of ellipse can now be specified as numpy.array

---

vispy/visuals/markers.py

In this PR, I changed the validation of marker symbols from quadratic to linear. 
The `self.symbol` is a list created from `self._symbol_shader_values`. So check if something is in O(n)
The `self._symbol_shader_values` is dict so checking if something is in in O(1)
Also python `all` is lazy when `np.all` is required to calculate all values. 
The problem was spotted in https://github.com/napari/napari/issues/6275

Improve Markers symbols validation performance

---

vispy/visuals/markers.py

This pull request follows issue 2546 (https://github.com/vispy/vispy/issues/2564). After further examining the original code, I found I misunderstood its purpose when I was writing the post. However, there is a bug in the original code, and I would like to restate it:
The (inferred) purpose of the original code:
In the original code, it is assumed that either edge_width or edge_width_rel is passed to set_data. 
If both are supplied, the method yields a ValueError. 
If neither is supplied, the method simply uses a default edge_width of 1.0. 
If either edge_width or edge_width_rel is supplied, it will be applied.
However, due to the default value of edge_width given in the definition of set_data, the function ends up with a ValueError when only edge_width_rel is supplied, which deviates …

Correction to Vispy.Visuals.Markers.set_data

---

vispy/visuals/volume.py

The integral computation in the attenuated MIP shader should *multiply* by the step size, rather than divide by it. That's how integrals work. 😅
**Edit:** Adding my longer description from comment below, which should go in the final commit message.
both before and after this change, increasing the attenuation increases the magnitude of the negative exponent and thus decreases the "scale" value, so the displayed value decreases in brightness (and closer values to the camera are favoured).
The reason we have never noticed anything wrong with this formula is that we have never before changed the relative step size, so there was just a division by a constant close to 1. Effectively a no-op.
But the division is in fact a bug, which is now obvious if you play with napari/napari#6930 with …

Fix integral computation in attenuated mip

---

vispy/visuals/volume.py

Having a really tiny step size is important when rendering very tiny volumes,
which otherwise show nasty sawtooth artifacts (napari/napari#3550). The value
of 0.1 seems pretty arbitrary, so here I just check that it's not 0 or
negative. We could set some much tinier epsilon but I don't see a principled
way of doing that...

Loosen bound on relative step size

---

vispy/visuals/volume.py

See discussion in #2589 
This changes the the `relative_step_size` setter to:
* raise a `ValueError` when setting to 0 or a negative value
* warn when setting small values between 0 and `side_len / (2 * MAX_CANVAS_SIZE)`
* silently comply otherwise
This is closer to the previous behavior, and I think makes intuitive sense (step size <=0 is non-sensical and could cause degenerate behavior in the shader).
A bit confusing - there is a test for this and it passed on #2589 checks:
https://github.com/vispy/vispy/blob/4f061ba23ddac3131eb0d1d955573dd71c9a3d2f/vispy/visuals/tests/test_volume.py#L46-L48

Raise ValueError when setting relative_step_size 0 or negative

---

.github/workflows/main.yml
doc/conf.py
vispy/io/tests/test_image.py
vispy/testing/_runners.py

I think I've sorted out the problem causing #2596. Sorry this is a lot to take in. I'm just trying to be thorough and keep track for my own purposes as well.
Before I write any more I'll try to be clear:
* _tests_ are the individual test functions in the test suite
* _checks_ are the the output of GitHub actions workflows
* _steps_ are the individual steps in a workflow
* _commands_ are the individual lines in a `run` step
The issue was that the GitHub actions workflow is replacing the default shell with `bash -l {0}`.
https://github.com/vispy/vispy/blob/4f061ba23ddac3131eb0d1d955573dd71c9a3d2f/.github/workflows/main.yml#L163-L166
This is problematic because it does not fail a run step if a command fails. I've changed the shell to `bash --login -e {0}` which will fail the run step if any …

Fix CI: failing tests and linting errors not failing checks

---

.github/workflows/wheels.yml
pyproject.toml
setup.py
vispy/geometry/__init__.py
vispy/geometry/calculations.py
vispy/geometry/triangulation.py
vispy/gloo/buffer.py
vispy/gloo/gl/tests/test_functionality.py
vispy/gloo/texture.py
vispy/testing/_testing.py
vispy/util/__init__.py
vispy/visuals/_scalable_textures.py
vispy/visuals/collections/array_list.py
vispy/visuals/image.py
vispy/visuals/text/_sdf_cpu.pyx

This introduces numpy 2.0 support. napari has started looking into support, and ran into a few small issues using vispy testing against it. See the [napari zulip thread](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/handling.20the.20numpy.202.2E0.20release/near/381330412) for some discussion and relevant links.
The process for adding support in this PR was:
* Run the ruff numpy 2.0 support check and fix:
```
ruff check vispy --select NPY201
ruff check vispy --select NPY201 --fix
```
* Run tests, fix issues and warnings
* Update for changes to behavior of the `copy` kwarg in `np.array`
* Add `vispy.util.np_copy_if_needed` value (`False` for numpy < 1.28, `None` for numpy >= 2.0)
* Search for `copy=False` used in `no.array` and remove it
* Search for `copy=copy` used in …

Add NumPy 2.0 support

---

vispy/visuals/_scalable_textures.py
vispy/visuals/tests/test_scalable_textures.py

I noticed this warning when running tests, and I think it traces back to the change in this PR.
```
vispy/visuals/tests/test_colormap.py: 6 warnings
vispy/visuals/tests/test_image.py: 39 warnings
vispy/visuals/tests/test_scalable_textures.py: 4 warnings
/Users/aandersoniii/src/vispy/vispy/gloo/texture.py:18: DeprecationWarning: finfo() dtype cannot be None. This behavior will raise an error in the future. (Deprecated in NumPy 1.25)
info = np.finfo(dtype)
```
See https://github.com/vispy/vispy/pull/2350#discussion_r1638869690 for some context.
I am partly guessing what this code meant to be doing, but here the `_data_dtype` is set the first time `scale_and_set_data` is called. @brisvag at your suggestion I am trying to think of a test that could have caught this, but need to think about it …

Set self._data_dtype in scale_and_set_data for CPU scaled textures

---

ci/requirements/linux_full_deps_conda.txt
vispy/visuals/tests/test_image.py

Continuation of #2611 
Matplotlib on conda-forge is now released with pyside6 instead of qt5. ~We either need to switch our default environment to pyside6, drop matplotlib as a dependency (no testing matplotlib features... :fearful: ), or do some other splitting of testing environments.~
~This PR does the first option, but this means Qt5-based backends are not tested at all in our CI anymore.~
This PR switches to matplotlib-base to not include the pyside6 dependency.
Thoughts?

Switch CI to use matplotlib-base

---

vispy/visuals/_scalable_textures.py

small change here.  I very frequently hit a ZeroDivisionError with scaling in vispy:
```python
File "/Users/talley/dev/self/orGANelle/.venv/lib/python3.12/site-packages/vispy/visuals/visual.py", line 505, in draw
if self._prepare_draw(view=self) is False:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/talley/dev/self/orGANelle/.venv/lib/python3.12/site-packages/vispy/visuals/image.py", line 677, in _prepare_draw
self._build_texture()
File "/Users/talley/dev/self/orGANelle/.venv/lib/python3.12/site-packages/vispy/visuals/image.py", line 613, in _build_texture
pre_clims = self._texture.clim_normalized
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/talley/dev/self/orGANelle/.venv/lib/python3.12/site-packages/vispy/visuals/_scalable_textures.py", line 296, in clim_normalized
clim_min = (clim_min - …
```

fix: prevent zerodiv error when auto-calculating clims in scalable textures

---

vispy/app/backends/_qt.py

Mouse Events forwarded from QT to the canvas events have a `modifers` attribute that is very useful to create enhanced interactions. For instance it can be used to make CONTROL + zoom behave like a slower zoom to better manipulate the camera.
Sadly when the QT event is a NativeGesture event, the current qt backend (_qt.py) does not forward this list of modifiers.
This PR fixes this so that we can have access to the modifiers when handling a QT native gesture event in vispy.
This PR just adds a `modifiers` attribute to these events, exactly as it's done with the classic mouse events. It works the same because QNativeGestureEvent inherits from QInputEvent (https://doc.qt.io/qtforpython-6/PySide6/QtGui/QInputEvent.html#PySide6.QtGui.QInputEvent) that has the `modifiers` method.
I couldn't …

Add modifiers to QT native gesture events

---

ci/requirements/linux_full_newqtdeps_apt.txt

This PR fixes CI failure due to runners now being Ubuntu 24.04:
https://github.com/vispy/vispy/actions/runs/12667848614/job/35302054335
libegl1-mesa was a transitional dummy package for libegl1, going back as far as 20.04
See equivalent fix here:
https://github.com/tlambert03/setup-qt-libs/pull/66

Update linux_full_newqtdeps_apt.txt fix CI for Ubuntu 24.04 runners

---

vispy/ext/cocoapy.py

Alternative to: https://github.com/vispy/vispy/pull/2549
This PR drops the monkeypatch because:
- The fix in ctypes for cdlls in bigsur is out in python >3.8:
https://bugs.python.org/issue41100
- The remaining issue was python 3.8, which has been dropped in https://github.com/vispy/vispy/pull/2599
Also, changes the name of the library to the proper `Quartz`, as per:
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html
The lower case may work due with case insensitive file system, but as noted by Ashley, with caching, it may fail.

Ensure proper `quartz` cdll loading on macOS (cocoapy)

---

vispy/geometry/triangulation.py

Since numpy 2.0 The `arr[ind]` is `np.int(64)`, not `int` that lead to not finding edge later when construct triangulation. 
This PR fixes it by converting it to python int.

Fix type of vertice passed to function for adding triangles

---

vispy/visuals/surface_plot.py
vispy/visuals/tests/test_surface_plot.py

Setting `colors` of `SurfacePlot` fails (see below code snippet).
```
from numpy.random import rand
p = scene.visuals.SurfacePlot(z=rand(6,6))
p.set_data(colors=rand(6,6,4))
```
Fix reshape of colors array to be with a length four last dimension.

Fix mesh colors reshaping

---

vispy/scene/cameras/arcball.py

Fixes #2641.
The arcball camera was using canvas coordinates instead of visual coordinates, which caused issues with viewboxes.

Use visual coordinates in ArcballCamera

---

vispy/app/backends/_qt.py

Currently, the Qt backend eats all events, regardless of whether vispy actually acts upon them. In my judgement, this seems contrary to the "best practices" of Qt, where events should be passed along if they are not acted upon.
This changeset calls [`QEvent.ignore()`](https://doc.qt.io/qt-6/qevent.html#ignore) in all of the relevant locations I could find (if there are some I missed, we should probably add this code there too), allowing parent widgets the chance to respond to unhandled events.
I'm wary about this change introducing other bugs, specifically in parent Qt widgets who are now receiving events they were not expecting - this changeset is likely a tradeoff that I think is worth consideration.
I'm not terribly sure whether this changeset warrants any changes to test code, and/or …

Ignore unhandled Qt events

---

vispy/color/colormap.py
vispy/color/tests/test_color.py
vispy/visuals/image.py
vispy/visuals/tests/test_image.py

Unfortunately I still had unresolved issues when merging #2659. That's what I get for not manually checking if things work one more time after changing "obvious" things...
The main issue is that the order of application of clim, gamma and bad_color were conflicting. By passing through NaN values to the colormap (the last to be applied) fixed and simplified the code significantly on the ImageVisual side.
Anyways, here's a functioning version. To test, use this snipped adapted from #2620:
```py
import sys
from vispy import scene, app
from vispy.color import get_colormap
canvas = scene.SceneCanvas(keys='interactive', bgcolor='white')
canvas.size = 600, 800
view = canvas.central_widget.add_view()
img_data = np.zeros((500, 500), np.float32)
for i in range(10): …
```

Fix bad_color handling and simplify some logic

---

vispy/geometry/meshdata.py
vispy/scene/cameras/base_camera.py
vispy/scene/cameras/panzoom.py
vispy/scene/cameras/perspective.py
vispy/scene/cameras/turntable.py
vispy/visuals/filters/mesh.py

See #2530 
CC @jintaoLee-roger
This is a collection of optimizations uncovered in #2530 debugging by me or @jintaolee-roger. The main ideas are to not update camera properties unless the value has actually changed. This prevents expensive transform-updating methods from being called unnecessarily. This is especially noticeable when a single camera move updates 4+ properties of a linked property and each one tries to report that the view/transform has changed. It does this in two ways:
1. Don't execute a transform update if we're updating properties
2. Don't update a property (and signal a view change) if the property value is the same
This PR also adds some checks in the mesh light filter to see if vertex normals have actually changed before submitting/uploading the normals to the GPU. It …

Various optimizations related to camera linking and mesh normals

---

ci/requirements/linux_full_deps_conda.txt

Continuing issue from #2636.
For context: there's currently some issue with the conda-forge package for pyopengl. It's causing several problems (not just our CI failures). We are in the process of figuring out the issue, but for the time being we just blacklist these versions here. This only affects CI and it allows us to actually cut a release.

Skip conda pyopengl 3.1.9

---

.github/workflows/wheels.yml

implements https://github.com/vispy/vispy/pull/2672#issuecomment-2882016826
github ref contains branch trigger name, so fon main it will be `refs/heads/main` but for tagged commit something like `refs/heads/tag` 
Each PR has a unique ref, but I left `event_type` for in-repo PRs

change cancelation policy of wheel workflow to base on ref

---

vispy/scene/widgets/grid.py

Following up #2671, I noticed that the `padding` was essentially disabled in the grid.
This was pretty simple to reenable!
Here's the code from the discussion in #2671 plus just `grid.padding = 20`:
cc @melonora

Fix padding in grid widget

---

vispy/scene/cameras/arcball.py

When using arcball camera and pressing shift to switch from rotating panning, if shift is released before the drag is finished, one receives this traceback:
```py
Traceback (most recent call last):
File ".../lib/site-packages/vispy/util/event.py", line 469, in _invoke_callback
cb(event)
File ".../lib/site-packages/napari/_vispy/camera.py", line 244, in viewbox_mouse_event
<class 'TypeError'> SceneMouseEvent type 'mouse_move' has no scale <traceback object at 0x000002867B3AFE00>
super().viewbox_mouse_event(event)
File ".../lib/site-packages/vispy/scene/cameras/perspective.py", line 233, in viewbox_mouse_event
self._update_rotation(event)
File ".../lib/site-packages/vispy/scene/cameras/arcball.py", line 65, in _update_rotation
Quaternion(*_arcball(self._event_value, wh)) *
File …
```

Only use last 2 event dimensions for arcball calculation

---

.github/workflows/wheels.yml
vispy/util/fonts/tests/test_font.py

Tests are failing because we're using an outdated windows runner.

Use newer windows runner in ci

---

.github/workflows/main.yml
ci/requirements/linux_full_deps_conda.txt

This reverts the pyopengl pin as in #2673 but adds a workaround that let CI pass in my fork.
As best I can understand the issue, pyopengl changed slightly the way it resolves shared libraries in https://github.com/mcfletch/pyopengl/pull/93 (v3.1.7+), which conflicts with how `sdl2` loads the same libraries or expects to find symbols in them...somehow. I can look into an upstream PR to pyopengl to resolve this, but that will take some time and I'm not super confident about making changes there (this is pretty convoluted for me to test).
This PR adds `LD_PRELOAD` (which I admit to not fully understanding) to change which symbols are prioritized when pyopengl loads openGL libraries.
I don't think anyone has reported these issues outside of CI, so I think this workaround is reasonable. If …

Revert pyopengl pin with `LD_PRELOAD` workaround
