- examples/basics/gloo/animate_shape.py
- examples/basics/gloo/rotate_cube.py
- examples/demo/gloo/mandelbrot_double.py
In my push to merge PRs, I merged too quickly, necessitating another PR :)
Ready for merge once Travis and AppVeyor come back happy.
> FIX: Flakify

- examples/benchmark/scene_test_1.py
- vispy/gloo/glir.py
- vispy/gloo/tests/test_program.py
- vispy/scene/widgets/widget.py
- vispy/testing/_runners.py
- vispy/util/event.py
- vispy/visuals/line/line.py
- vispy/visuals/shaders/function.py
- vispy/visuals/transforms/linear.py
WIP: This PR adds a benchmark example for comparing scenegraph performance to similar optimal implementations. 
The intent is to add more benchmark examples and optimizations until we get comparable performance (or decide that we will never get comparable performance).
> Scenegraph benchmark

- vispy/visuals/glsl/color.py
> Add HSV<->RGB GLSL functions

- vispy/gloo/tests/test_buffer.py
- vispy/scene/canvas.py
- vispy/scene/visuals/tests/test_rect_polygon.py
- vispy/testing/_testing.py
- vispy/visuals/tests/test_ellipse.py
- vispy/visuals/tests/test_polygon.py
- vispy/visuals/tests/test_rectangle.py
- vispy/visuals/tests/test_text.py
We'll see if Travis and AppVeyor are happy. Tests pass on my Windows machine.
> ENH: Improved testing

- vispy/color/color_array.py
- vispy/scene/widgets/widget.py
- vispy/visuals/ellipse.py
- vispy/visuals/line/line.py
- vispy/visuals/polygon.py
- vispy/visuals/rectangle.py
- vispy/visuals/regular_polygon.py
> Corrected improper use of Color.is_blank  (fixes scene/viewbox example)

- examples/basics/scene/grid_large.py
- examples/basics/scene/image.py
- examples/basics/scene/isocurve.py
- examples/basics/scene/line_update.py
- examples/benchmark/simple_vispy.py
- vispy/app/backends/_qt.py
- vispy/app/canvas.py
- vispy/color/__init__.py
- vispy/gloo/gl/desktop.py
- vispy/gloo/gl/es2.py
- vispy/gloo/gl/pyopengl.py
- vispy/gloo/globject.py
- vispy/gloo/program.py
- vispy/io/__init__.py
- vispy/plot/__init__.py
- vispy/testing/_runners.py
- vispy/util/dpi/__init__.py
- vispy/util/wrappers.py
- vispy/visuals/transforms/__init__.py
- vispy/visuals/transforms/base_transform.py
@almarklein ready for review/merge assuming Travis is happy. The PEP8 program was updated with new rules, and this ignores one of them and brings us into compliance with the others.
> FIX: Update for new pep8

- vispy/visuals/tests/test_markers.py
This will help us know whether or not point sprites are working for people.
> ENH: Simple marker test

- examples/tutorial/app/app_events.py
- vispy/ext/mplutils.py
- vispy/geometry/generation.py
- vispy/visuals/isoline.py
- vispy/visuals/markers.py
- vispy/visuals/shaders/parsing.py
- vispy/visuals/shaders/tests/test_parsing.py
Should make Travis happy again.
> FIX: Minor fixes

- examples/tutorial/app/shared_context.py
Fixes the shared context example. Ready for review/merge.
> FIX: Fix example

- examples/basics/plotting/scatter.py
- vispy/plot/__init__.py
- vispy/plot/plot.py
- vispy/visuals/markers.py
Hello all,
I just made a prototype for scatter().
**Bug below has been fixed**
It works but there is still a problem that we need to zoom or change the view to see all points.
If you run the code below:
```bash
>>> import vispy.plot as pl
>>> pl.scatter([1, 2, 3, 4])
```
The pic that we want to get is:
but we get:
> Add plot.scatter

- make/make.py
- vispy/testing/_runners.py
you can invoke it in two ways:
```
python make test examples
``` 
``` 
python make test examples examples/demo/gloo/mandelbrot.py  examples/demo/gloo/graph.py examples/demo/scene/magnify.py 
````
Hope this is okay.
If there are any changes that need to be done, please do tell me
> add support to run individual examples into the testing framework

- examples/demo/gloo/galaxy/galaxy.py
- examples/demo/gloo/galaxy/galaxy_simulation.py
- examples/demo/gloo/galaxy/galaxy_specrend.py
Ported the [Galaxy demo from glumpy](https://github.com/glumpy/glumpy/blob/master/examples/galaxy.py) to ```VisPy```
This depends on the 1D sampler implemented [in this pull request](https://github.com/vispy/vispy/pull/737). So please make sure to pull that first before merging this example change.
I've tried to comment the example as meaningfully as possible so that the code is easy to follow.
Images:
> Galaxy demo

- examples/demo/gloo/realtime_signals.py
> fix scaling - scale around center, not right end of signal

- vispy/color/color_array.py
- vispy/color/tests/test_color.py
implemented the [feature request](https://github.com/vispy/vispy/issues?q=hsvis%3Aissue+is%3Aopen+) to allow hsv parameters to ```ColorArray```
closes #692
> added hsv parameter to ColorArray

- vispy/visuals/image.py
> Fix vispy.plot.image fails on float64 textures

- examples/basics/scene/viewbox.py
- examples/tutorial/visuals/01_basic_visual.py
- examples/tutorial/visuals/02_measurements.py
- examples/tutorial/visuals/03_antialiasing.py
- examples/tutorial/visuals/04_fragment_programs.py
- examples/tutorial/visuals/05_viewer_location.py
- vispy/gloo/buffer.py
- vispy/scene/cameras/cameras.py
- vispy/util/transforms.py
- vispy/visuals/transforms/linear.py
WIP: a set of tutorials that cover the basics of writing Visual classes:
* Using doc coordinates to make physical measurements
* Using framebuffer coordinates for antialiasing
* Using inverse transforms from the fragment shader
* Determining the camera direction (for material shading, volumes, etc.)
Presently I am hung up trying to fix some issues with the camera and projection transforms. 
I'd be glad to take requests for other tutorials..
> Visual tutorial

- vispy/app/base.py
Check before attempting to access attributes of an object that may not exist
> Error in Mouse handling

- vispy/gloo/glir.py
> Fix gallaxy/galaxy.py example

- examples/basics/gloo/display_points.py
- vispy/gloo/buffer.py
- vispy/gloo/program.py
- vispy/gloo/tests/test_program.py
- vispy/visuals/gridlines.py
- vispy/visuals/mesh.py
Closes #503.
Should be ready for review/merge, but I'll wait until the CIs are happy to ping.
> FIX: Check vbo size

- vispy/gloo/glir.py
- vispy/gloo/globject.py
- vispy/gloo/tests/test_globject.py
This should fix some memory issues.
> When gloo object dies, delete associated GPU object

- README.rst
- vispy/gloo/buffer.py
- vispy/gloo/tests/test_buffer.py
- vispy/testing/__init__.py
- vispy/util/fetching.py
Also contains a minor fix for the downloading. Will ping once the CIs are happy.
Closes #691.
Closes #711.
> FIX: Raise error for 64-bit float

- vispy/gloo/glir.py
- vispy/gloo/program.py
- vispy/gloo/tests/test_program.py
- vispy/gloo/tests/test_use_gloo.py
> FIX: Uniform array support

- examples/basics/scene/flipped_axis.py
- vispy/scene/cameras/cameras.py
PanZoom can thus operate in any plane, Turntable can be tilted in any plane, and FlyCamera will attempt to re-orient to make up point upward.
> All cameras now handle the "up" property correctly

- vispy/scene/cameras/cameras.py
This copies the way right click zooming is handled.
> Made scroll wheel zoom work when fov > 0

- examples/basics/gloo/animate_images_slice.py
- examples/basics/scene/volume.py
- vispy/gloo/__init__.py
- vispy/gloo/texture.py
- vispy/visuals/shaders/parsing.py
- vispy/visuals/shaders/program.py
- vispy/visuals/volume.py
Someone else should review this, especially the emulated 3D texture and its indexing schemes. It's worth trying for all kinds of crazy max_texture_sizes to make sure everything works. 
@rougier basically wrote the sample, so I'm ccing him here
> Emulated 3D textures

- doc/user_guide.md
* This is not a full user guide but already a starting point
* This is Markdown because I hate ReST, but if needed it can be converted with `pandoc -f markdown -t rst user_guide.md -o user_guide.rst`
* There are many TODOs that could be tackled later.
* Closes #803
> Add user guide

- examples/collections/choropleth.py
- examples/geojson.py
- vispy/geometry/__init__.py
- vispy/geometry/triangulation.py
- vispy/visuals/collections/raw_polygon_collection.py
* Added a `triangulate()` function. It uses the C++ [triangle](https://github.com/drufat/triangle) library if it is available, or it gracefully falls back to the pure Python version otherwise. triangle doesn't work with Python 3, although the master version on GitHub does. I get some stochastic segmentation faults on the tiger example with triangle.
* Will need to use a proper map projection method later.
* Closes #795.
> Choropleth example

- examples/basics/scene/console.py
- examples/basics/scene/grid.py
- examples/basics/scene/grid_large.py
> FIX: Fix missing cameras

- examples/basics/gloo/display_lines.py
- examples/basics/gloo/post_processing.py
- examples/basics/gloo/rotate_cube.py
- examples/basics/scene/one_scene_four_cams.py
- examples/demo/gloo/atom.py
- examples/demo/gloo/brain.py
- examples/demo/gloo/cloud.py
- examples/demo/gloo/donut.py
- examples/demo/gloo/galaxy.py
- examples/demo/gloo/galaxy/galaxy.py
- examples/demo/gloo/glsl_sandbox_cube.py
- examples/demo/gloo/molecular_viewer.py
- examples/demo/gloo/terrain.py
- examples/tutorial/gloo/colored_cube.py
- examples/tutorial/gloo/lighted_cube.py
- examples/tutorial/gloo/outlined_cube.py
- examples/tutorial/gloo/textured_cube.py
- vispy/app/timer.py
- vispy/scene/cameras/cameras.py
- vispy/scene/widgets/viewbox.py
- vispy/util/tests/test_transforms.py
- vispy/util/transforms.py
- vispy/visuals/transforms/_util.py
- vispy/visuals/transforms/linear.py
- vispy/visuals/transforms/nonlinear.py
- vispy/visuals/tube.py
Closes #97.
Closes #507.
Not ready for merge since it doesn't seem to work quite right yet...
> ENH: Unify transforms

- vispy/scene/events.py
- vispy/scene/widgets/console.py
- vispy/visuals/text/text.py
- vispy/visuals/transforms/transform_system.py
@nippoo see if this works.
Closes #511.
> ENH: Text and console using doc coord sys

- examples/benchmark/scene_test_1.py
- examples/demo/gloo/galaxy/galaxy.py
- examples/demo/gloo/shadertoy.py
- examples/tutorial/app/app_events.py
@nippoo can you see if this fixes #801 for you? It also moves us toward fixing #826, but isn't quite there yet. (I need to do more work on GLFW on OSX to really fix that probably.)
> FIX: Minor example fixes

- vispy/ext/gdi32plus.py
- vispy/util/dpi/_win32.py
Closes #715.
Ready for review/merge, @almarklein might be quickest for you.
> FIX: Fix for Windows XP

- codegen/annotations.py
- examples/tutorial/gl/cube.py
- examples/tutorial/gl/fireworks.py
- examples/tutorial/gl/quad.py
- vispy/app/backends/_glfw.py
- vispy/app/canvas.py
- vispy/app/tests/test_simultaneous.py
- vispy/app/timer.py
- vispy/gloo/gl/_pyopengl2.py
- vispy/util/dpi/_linux.py
- vispy/util/dpi/_quartz.py
- vispy/util/dpi/_win32.py
- vispy/util/fetching.py
@nippoo can you see if the examples you mention in #806 work with this PR?
Closes #838.
Closes #837.
Closes #806.
Closes #667.
Closes #630.
Closes #576.
> FIX: Minor fixes to GL tutorial examples

- vispy/ext/freetype.py
- vispy/geometry/__init__.py
- vispy/geometry/calculations.py
- vispy/geometry/tests/test_calculations.py
- vispy/testing/_testing.py
- vispy/visuals/line/line.py
- vispy/visuals/tests/test_ellipse.py
- vispy/visuals/tests/test_polygon.py
- vispy/visuals/tests/test_rectangle.py
- vispy/visuals/tests/test_regular_polygon.py
Closes #789.
Closes #551.
@nippoo can you see if this makes tests pass for you?
> FIX: HiDPI testing

- examples/demo/gloo/molecular_viewer.py
- vispy/gloo/glir.py
- vispy/gloo/tests/test_glir.py
Squashed #855, will merge if the CIs are happy
> Updated JSON logger

- vispy/util/fonts/tests/test_font.py
This should make it so we have fewer strange errors. @campagnola can't replicate, and I'll check on Monday but I doubt I'll be able to either. I think we're probably okay on this one -- I'll merge if Travis comes back happy so that this doesn't impede our progress so much.
> FIX: Fix silly error

- examples/basics/scene/cube.py
- examples/basics/scene/flipped_axis.py
- examples/basics/scene/viewbox.py
- examples/basics/scene/volume.py
- examples/basics/visuals/arcball.py
- vispy/geometry/meshdata.py
- vispy/scene/cameras/__init__.py
- vispy/scene/cameras/cameras.py
- vispy/util/quaternion.py
> ENH: Arcball

- examples/basics/scene/colored_line.py
- examples/basics/scene/flipped_axis.py
- examples/basics/scene/grid.py
- examples/basics/scene/grid_large.py
- examples/basics/scene/nested_viewbox.py
- examples/basics/scene/text.py
- examples/basics/scene/viewbox.py
- examples/basics/scene/volume.py
- examples/basics/visuals/line.py
- vispy/mpl_plot/_mpl_to_vispy.py
- vispy/scene/widgets/widget.py
- vispy/visuals/isocurve.py
- vispy/visuals/isoline.py
- vispy/visuals/line/line.py
- vispy/visuals/tests/test_volume.py
- vispy/visuals/volume.py
- vispy/visuals/xyz_axis.py
Rebase of #853, will merge if the CIs are happy
> Consistent use of method

- examples/basics/scene/sensitivity.py
- examples/demo/scene/magnify.py
- vispy/scene/cameras/cameras.py
- vispy/visuals/text/text.py
We rushed the volume PR through and let a few things slip. This addresses some of them..
> Camera cleanup

- vispy/app/backends/_qt.py
Ready for review/merge. Fixes #886.
> Set focus policy in Qt widget

- examples/demo/gloo/primitive_mesh_viewer_qt.py
Fix problem with new transform system
> Fix issue #885

- vispy/visuals/shaders/function.py
- vispy/visuals/shaders/program.py
- vispy/visuals/shaders/shader_object.py
- vispy/visuals/shaders/tests/test_function.py
Improves performance in many examples, hopefully fixes #888.
@inclement can you verify this helps?
> Defer string formatting in log messages

- vispy/app/backends/_qt.py
- vispy/app/backends/_template.py
- vispy/app/backends/_wx.py
- vispy/app/base.py
- vispy/app/canvas.py
- vispy/app/tests/test_backends.py
> Double-click

- examples/basics/scene/background_borders.py
- examples/basics/scene/colored_line.py
- vispy/scene/node.py
- vispy/scene/widgets/grid.py
- vispy/scene/widgets/viewbox.py
- vispy/scene/widgets/widget.py
- vispy/testing/image_tester.py
Closes #908.
@KelSolaar can you see if this fixes your use case?
@campagnola feel free to have a look and see if you agree with the changes.
> FIX: Fix background colors

- vispy/gloo/gl/gl2.py
Closes #929.
This was easier than I expected (I think). Ready for review/merge @rossant.
> FIX: Dont require gl lib

- vispy/visuals/tests/test_text.py
- vispy/visuals/text/text.py
Ready for review/merge @campagnola.
@nippoo with this PR you can do:
```
text.text = ['foo', 'bar']
text.pos = [[100, 200], [100, 300]]
canvas.update()
```
and it should show both bits of text.
> FIX: Allow text lists

- vispy/scene/cameras/cameras.py
> FIX #937 left Click and shif key 

- vispy/util/svg/color.py
Filling the dictionary now takes about half the time too!
> rewrite dictionary comprehension as a loop (Python 2.6 support)

- .gitignore
- .travis.yml
- make/make.py
- vispy/app/tests/test_app.py
- vispy/testing/__init__.py
- vispy/testing/_runners.py
- vispy/testing/_testing.py
- vispy/testing/image_tester.py
- vispy/util/logs.py
- vispy/visuals/line/line.py
- vispy/visuals/tests/test_rectangle.py
- vispy/visuals/tests/test_volume.py
Closes #875
Closes #866
Closes #935
> FIX: Plot in WebGL and testing

- README.rst
Ready for review/merge, just a line about release announcement that @almarklein mentioned in #903
> FIX: Update README [ci skip]

- vispy/app/application.py
- vispy/app/backends/_qt.py
- vispy/app/base.py
- vispy/app/inputhook.py
- vispy/app/tests/test_backends.py
closes #945 
an attempt to use @campagnola and @Eric89GXL's suggestions to help reduce the performance impact of running vispy interactively
> [WIP] Fix vispy performance when used in the python interpreter

- vispy/mpl_plot/_mpl_to_vispy.py
Closes #962. Ready for review/merge from my end.
> FIX: Fix mpl_plot

- vispy/util/config.py
> fixed doc string for pyqt5

- vispy/gloo/glir.py
Only give a warning if OpenGL < 2.1. Ready for review/merge from my end.
> FIX: Fix OpenGL message

- vispy/visuals/volume.py
Proposal to add a sanity check to the contrast limits range.
Avoids division by zero when clim is set from the volume data, and the data is a 'brick' (every voxel the same value)
> Add volume check

- vispy/ext/fontconfig.py
- vispy/ext/freetype.py
- vispy/util/fonts/_freetype.py
- vispy/util/fonts/_win32.py
- vispy/util/fonts/tests/test_font.py
> FIX: More font tests

- vispy/app/_default_app.py
- vispy/testing/_runners.py
- vispy/testing/_testing.py
I noticed our testing suite was not efficiently skipping backends that aren't installed or don't work, this should fix it.
> FIX: Better skipping

- .travis.yml
Let's see if we can speed up the build system.
> ENH: Use container-based infrastructure

- README.rst
Missed this bit when I made the PR earlier. Ready for review/merge from my end.
> FIX: Fix core

- examples/basics/scene/line_update.py
- examples/basics/scene/nested_viewbox.py
- examples/basics/scene/one_cam_two_scenes.py
- examples/demo/scene/oscilloscope.py
- vispy/scene/cameras/fly.py
- vispy/scene/canvas.py
- vispy/scene/node.py
- vispy/scene/visuals.py
- vispy/scene/widgets/widget.py
WIP: addressing reviewer comments
> Scenegraph update - review

- examples/basics/scene/point_cloud.py
> create simplest scene-based 3D point cloud example. Closes #1028

- .travis.yml
- appveyor.yml
- make/install_python.ps1
- vispy/visuals/rectangle.py
- vispy/visuals/tests/test_colorbar.py
A few minor fixes, and allows us to ensure we're staying compatible with old `numpy`.
> MRG: Minor fixes

- README.rst
I thought I should update the notes on `Installation` in the `README` to help newbies, so we could just point people to a set of pre-written steps
> [WIP] Install notes update

- examples/basics/scene/sphere.py
- vispy/geometry/generation.py
- vispy/geometry/tests/test_generation.py
- vispy/visuals/sphere.py
> ENH: Implement icosphere for uniform sphere tessellation

- examples/basics/gloo/spatial_filters.py
- examples/basics/scene/contour.py
- vispy/glsl/build-spatial-filters.py
- vispy/glsl/misc/spatial-filters.frag
- vispy/io/datasets.py
- vispy/visuals/filters/__init__.py
- vispy/visuals/filters/color.py
- vispy/visuals/image.py
to fix precision issues, fixes #1068
This fixes problems with ImageVisual using spatial filtering using 1D kernel lookups.
> FIX: change kernel texture internalformat and interpolation 

- examples/demo/gloo/quiver.py
This makes the vector field plot look nicer.
> Add blending to improve the look of the vector field plot.

- vispy/testing/image_tester.py
Fixes #1147 
Should I add a test for `image_tester` as well? (I see where this is going - "who will watch the watchers").
> BUG: changed image_tester so it doesn't try to overwrite frozen classes

- vispy/app/backends/_qt.py
This adds preliminary multitouch support on OS X (Qt backend). It works fine on my end so it should be ready to go.
cc @Eric89GXL @nippoo
> Add touch event on OS X

- vispy/app/base.py
> Discard mouse events that are too close

- vispy/testing/image_tester.py
- vispy/util/fetching.py
> Use http instead of https to get demo data

- vispy/gloo/glir.py
- vispy/gloo/program.py
I was unable to get boolean uniforms to work in my shaders until I made these changes. I have somehow managed to lose my code that could reproduce the error, sorry :(. What kind of test can I add that will verify this doesn't break in the future? I'm super new to working with GL and vispy so I'm not quite sure what's appropriate for getting this merged, so any help would be much appreciated!
> Fix boolean uniforms in GLIR

- vispy/io/mesh.py
- vispy/io/tests/test_io.py
- vispy/io/wavefront.py
Here we go.
Not sure the tests are correctly or sensibly written. Also not sure if one can (and should) test if a warning is raised.
Waiting for comments!
> Added support for writing non-triangular meshes in .OBJ files -- GH #1155

- vispy/plot/plotwidget.py
- vispy/visuals/colorbar.py
- vispy/visuals/image.py
Fixes for issues raised in [#1203](https://github.com/vispy/vispy/issues/1203)
> Minor bugfixes

- vispy/app/backends/_ipynb_webgl.py
- vispy/app/backends/_osmesa.py
- vispy/app/backends/_qt.py
- vispy/app/backends/ipython/_widget.py
- vispy/geometry/_triangulation_debugger.py
- vispy/glsl/__init__.py
- vispy/ipython/ipython.py
- vispy/testing/_runners.py
- vispy/util/svg/group.py
- vispy/util/wrappers.py
- vispy/visuals/collections/agg_fast_path_collection.py
- vispy/visuals/collections/agg_path_collection.py
- vispy/visuals/collections/agg_point_collection.py
- vispy/visuals/collections/agg_segment_collection.py
- vispy/visuals/collections/base_collection.py
- vispy/visuals/collections/raw_path_collection.py
- vispy/visuals/collections/raw_point_collection.py
- vispy/visuals/collections/raw_polygon_collection.py
- vispy/visuals/collections/raw_segment_collection.py
- vispy/visuals/collections/raw_triangle_collection.py
Closes https://github.com/vispy/vispy/issues/1218
> Change any absolute imports to relative imports for consistency

- .gitmodules
As asked by @Eric89GXL in #1215, this PR binds the documentation (now maintained in a different repository) to the source tree via a git submodule.
> Add documentation as a git-submodule.

- examples/basics/scene/grid_large.py
- vispy/geometry/generation.py
- vispy/io/datasets.py
- vispy/scene/widgets/colorbar.py
- vispy/scene/widgets/grid.py
- vispy/testing/_runners.py
- vispy/visuals/graphs/graph.py
- vispy/visuals/infinite_line.py
- vispy/visuals/isosurface.py
- vispy/visuals/linear_region.py
- vispy/visuals/sphere.py
Hopefully this makes Travis happy
> FIX: Fix docstrings

- examples/basics/scene/axes_plot.py
- examples/basics/scene/nested_viewbox.py
- examples/basics/visuals/arrows_quiver.py
- examples/basics/visuals/line.py
- examples/demo/gloo/grayscott.py
- examples/demo/scene/flow_lines.py
- examples/demo/scene/force_directed_graph.py
- vispy/visuals/axis.py
- vispy/visuals/collections/base_collection.py
- vispy/visuals/collections/raw_point_collection.py
It would be nice to have an easy way to add an axis label (in addition to the tick labels) for the AxisVisual class. This PR is a very rough implementation of that. Currently this looks like:
The text is always lined up with the screen. There are still several things to do to make this acceptable in my opinion. For example we need to choose a spacing from the axis to the label that depends on the font size and can be overriden by the user.
However, even then it might not be very pretty. Does anyone have suggestions on how we could do this better?
cc @PennyQ
> Axis label for AxisVisual class

- vispy/app/backends/_glfw.py
- vispy/app/backends/_sdl2.py
> glfw and sdl2 multi canvas fix

- examples/basics/scene/colorbar_widget.py
- vispy/plot/plotwidget.py
- vispy/scene/widgets/colorbar.py
- vispy/visuals/colorbar.py
closes #1251 
As written in the above issue, there are some glitches using ColorBarWidget/ColorBarVisual. I tried to address all  issues mentioned.
Main thing is that the labels and colors are propagated to the Textvisuals and they are exposed (somehow) to the upper layers for easy change.
> MIN: fix several issues with ColorBarWidget/ColorBarVisual

- examples/demo/gloo/voronoi.py
Fix for Retina displays (mentioned in #99)
Also adding a mouse_press callback!
> Fix for Retina displays

- examples/demo/scene/oscilloscope.py
> FIX: demo/scene/oscilloscope.py

- vispy/scene/cameras/arcball.py
add _quaternion to camera state properties to share rotations.
> Fix arcball camera linking

- vispy/app/backends/_wx.py
> wx: delete the deprecated call EventLoop

- vispy/app/backends/_wx.py
> wx: fix using a default position of canvas

- examples/tutorial/app/simple_wx.py
> examples: fix simple app

- examples/collections/triangle_collection.py
- vispy/geometry/triangulation.py
- vispy/visuals/collections/agg_fast_path_collection.py
- vispy/visuals/collections/agg_path_collection.py
Fix #1340.
If you have a chance @ThomJea it would be great if you could test this too.
> Fix collections for python 3

- make/make.py
See https://github.com/vispy/vispy-website/pull/7
> Fix doc website creation using the wrong README file extension

- examples/basics/plotting/colorbar.py
- examples/basics/plotting/grid_basic.py
- examples/basics/plotting/grid_holed.py
- examples/basics/plotting/grid_uneven_col.py
- examples/basics/plotting/grid_x_y_viewbox.py
- examples/basics/scene/axes_plot.py
- examples/basics/scene/colorbar_widget.py
- examples/basics/scene/contour.py
- examples/demo/scene/scrolling_plots.py
- make/make.py
- vispy/visuals/scrolling_lines.py
- vispy/visuals/transforms/nonlinear.py
Includes fixes to `scrolling_plots.py`. See commit messages for details.
> Fix gallery generation

- vispy/__init__.py
- vispy/visuals/line/line.py
- vispy/visuals/transforms/transform_system.py
Didn't do this during release process and should have.
> Update version to 0.6.0dev0 and small doc issues

- vispy/app/backends/_qt.py
> Fix HiDPI issue in pyqt5

- vispy/util/dpi/_linux.py
> Fix DPI calculation when xrandr reports screen dimension of 0mm

- vispy/app/backends/_pyglet.py
Mouse scroll event reported wrong position
> Fix zoom event position in Pyglet backend

- vispy/scene/cameras/__init__.py
> DOC: add __all__ string to scene/cameras/__init__.py

- examples/demo/gloo/two_qt_widgets.py
closes #1298 
Note: This Example uses PyQt4 but this also works with PyQt5
> MIN: add two_qt_widgets in examples/demo/gloo 

- vispy/gloo/glir.py
> FIX: fix order of alignment values for proper processing

- vispy/io/mesh.py
- vispy/io/stl.py
See https://github.com/vispy/vispy/issues/1425
> Adding capability to load STL file with read_mesh function.

- Makefile
- README.rst
- make/make.py
- setup.py
- vispy/app/backends/__init__.py
- vispy/app/backends/_pyqt4.py
- vispy/app/backends/_pyqt5.py
- vispy/app/backends/_pyside.py
- vispy/app/backends/_pyside2.py
- vispy/app/backends/_qt.py
- vispy/app/qt.py
- vispy/app/tests/test_backends.py
- vispy/util/config.py
- vispy/util/tests/test_import.py
- vispy/util/wrappers.py
You can build pyside2 yourself or use
https://github.com/fredrikaverpil/pyside2-linux
I mostly searched for PySide and PyQt5 and kinda merged them together.
it ran the `examples/basics/scene/grid.py`, `magnify.py` and `cube.py`. Good enough for a first day. Haven't tested other things yet. But I think it is OK :D.
I had to add a `qWait` function.
I have no idea what `has_uic` is
> First attempt at PySide2 support

- appveyor.yml
> FIX: Reenable coveralls

- vispy/util/filter.py
This is/was causing failing examples tests on travis.
> Fix FutureWarning in gaussian_filter indexing

- vispy/visuals/filters/base_filter.py
- vispy/visuals/filters/clipper.py
- vispy/visuals/filters/color.py
- vispy/visuals/filters/picking.py
- vispy/visuals/transforms/linear.py
Provides a new filter base-class and re-implements most filters.
These changes include the following:
~~- freezes all filter attributes to prevent incorrect assignment which can occur when switching filters (see #1518)~~
- implements the `_detach` method for proper filter detachment (see #1522 and #1434)
closes #1522 
closes #1434
> Re-implement vispy-provided filters

- vispy/app/backends/_glfw.py
> passing title as encode('utf-8') in glfwSetWindowTitle

- vispy/plot/plotwidget.py
Add kwarg `connect` to lines at plot level.
> Add connect to line plot

- vispy/plot/fig.py
As the docstring said "diagonal line".
> Fix a typo

- vispy/util/transforms.py
I just did a minor correction of the documentation of the `rotate()` transform function.
> Correct documentation

- .travis.yml
- vispy/app/backends/_qt.py
- vispy/color/tests/test_color.py
- vispy/gloo/gl/_pyopengl2.py
- vispy/gloo/tests/test_framebuffer.py
- vispy/scene/widgets/grid.py
- vispy/visuals/axis.py
- vispy/visuals/colorbar.py
This fixes #1568 alongside with https://github.com/mcfletch/pyopengl/pull/20
> FIX: fix pyopengl and osmesa

- examples/demo/scene/klein.py
- vispy/geometry/normals.py
- vispy/geometry/parametric.py
This PR try to adress #819
The code so far is really basic, feel free to tell me what you think, I'm ready to work on it.
And I'm not even sure where to put the example?
> Klein bottle example

- examples/basics/scene/turntable_box.py
- examples/basics/visuals/arcball.py
- examples/basics/visuals/rotating_box.py
- vispy/visuals/cube.py
Check issue https://github.com/vispy/vispy/issues/1549
> Remove cube visual in favor of box visual

- vispy/geometry/triangulation.py
> Make sure segments have the right format

- vispy/visuals/sphere.py
The goal of this PR is to enable the `shading` capabilities of the `vispy.visuals.SphereVisual`.
Some tweaking might be needed, tell me what do you think?
> Add shading to SphereVisual

- vispy/scene/cameras/arcball.py
- vispy/scene/cameras/turntable.py
Add translate_speed keyword argument to turntable and arcball cameras
> Add 'translate_speed' to TurntableCamera and ArcballCamera

- vispy/visuals/xyz_axis.py
**What does this implement/fix?**
This PR tries to fix  #671 by allowing the override of defaults `pos` and `color` arguments.
**Additional information**
Maybe overriding `connect` and `method` is too much?
> [MRG] Allow XYZAxisVisual override of position, color, connect, and method

- examples/basics/visuals/windbarb_quiver.py
- examples/basics/visuals/windbarbs.py
- vispy/scene/visuals.py
- vispy/testing/image_tester.py
- vispy/visuals/__init__.py
- vispy/visuals/tests/test_windbarb.py
- vispy/visuals/windbarb.py
This is a follow up PR from #1563. 
This adds a special WindbarbVisual as well as an example. The Visual might need some tweaking here and there. Would be nice if someone can test and review. There is also shader code which can be moved to the gsls subfolder (see also #1566).
Ping @sjoro and @rougier.
@larsoner @djhoese How and where should I add tests for this? Is the example tested anyway?
> Add WindbarbVisual

- vispy/scene/cameras/arcball.py
- vispy/scene/cameras/perspective.py
- vispy/scene/cameras/turntable.py
> Fix depth buffer precision

- vispy/visuals/mesh.py
- vispy/visuals/tests/test_mesh.py
This PR side-steps an `IndexError: list index out of range` error that happens when swapping cameras on 2D mesh. If desired I can come up with a minimal reproducible example purely using vispy code, but we've been encountering it quite a bit in napari - see https://github.com/napari/napari/issues/672 for the latest time. We might be using the cameras in a bad way to be triggering it, but what is happening is that we're asking for scene bounds for `axis=[0, 1, 2]`, but our mesh is 2D and so one is missing. We get the following error:
```bash
File "/Users/nicholassofroniew/Github/napari/napari/_qt/qt_viewer.py", line 177, in _update_camera
aspect=1, name="PanZoomCamera"
File "/anaconda3/lib/python3.7/site-packages/vispy/util/frozen.py", line 17, in __setattr__
object.__setattr__(self, key, …
```
> mesh bounds index error

- vispy/visuals/axis.py
This adds getters and setters for a number of properties related to the appearance of the ``AxisVisual``. Also enables anti-aliasing for axis lines and ticks.
> Improve AxisVisual visual by providing property getters and setters

- vispy/geometry/triangulation.py
- vispy/visuals/isocurve.py
- vispy/visuals/transforms/tests/test_transforms.py
Addressing @cgohlke's [comment](https://github.com/vispy/vispy/issues/1779#issuecomment-561366474).
> FIX: Nest triangle and skimage imports

- vispy/app/backends/_ipynb_vnc.py
> Fix simple typo: withour -> without

- vispy/app/backends/_qt.py
Workaround for https://github.com/vispy/vispy/issues/1787
> Filter away annoying qnotifier warning.

- pyproject.toml
> Unpin numpy for Py>=3.7.

- appveyor.yml
- examples/basics/scene/isocurve_for_trisurface_qt.py
- examples/demo/gloo/imshow_cuts.py
- examples/demo/gloo/primitive_mesh_viewer_qt.py
- examples/demo/gloo/unstructured_2d.py
- examples/demo/scene/oscilloscope.py
- examples/demo/visuals/wiggly_bar.py
- vispy/geometry/torusknot.py
This PR fixes running examples with recent versions of numpy (`>= 1.18`)
(mostly related to https://github.com/numpy/numpy/pull/14620)
> Fix examples with recent numpy version

- azure-pipelines.yml
- setup.py
Taking the advice from @larsoner for fixing this. See https://github.com/mne-tools/mne-python/pull/7457
> Fix PRs not being run on Azure

- vispy/color/_color_dict.py
> Add "transparent" color to internal color_dict

- vispy/plot/plotwidget.py
- vispy/visuals/spectrogram.py
- vispy/visuals/tests/test_spectrogram.py
The PR adds ability to the spectrogram visual to modify the parameters after the first draw.
> Allow changing spectrogram parameters after it has been drawn

- examples/basics/visuals/grid_mesh.py
- examples/offscreen/simple_osmesa.py
- setup.cfg
- vispy/geometry/isocurve.py
- vispy/testing/__init__.py
- vispy/visuals/collections/array_list.py
- vispy/visuals/graphs/graph.py
- vispy/visuals/transforms/linear.py
Flake8 3.8.x was released in the last week and it is causing some new failures on Travis. This PR is my attempt at fixing these issues in the most reasonable manner. The majority of the issues were ambiguous variable names which is a pretty good thing to check for in my opinion so I didn't want to outright ignore that rule. There were a few cases where it made sense to have a variable named `l` (like left, right, bottom, top function arguments) and other cases where it was just laziness that was easy to fix. In one case (`husl.py`) it is technically an external library so I ignored that file in `setup.cfg`.
> Fix styling issues due to new flake8 version

- .travis.yml
- examples/basics/visuals/axially_symmetric_surfaces.py
- vispy/visuals/surface_plot.py
The SurfacePlot() function can now accept user created mesh. This enables drawing surfaces using cylindrical and spherical cooordinates. An example code is also added which may be accepted after review.
> Allow for 2D X and Y coordinates in SurfacePlotVisual

- vispy/app/backends/ipython/_widget.py
Bump ipython widget to match package.json
> Fix jupyter lab extension to use newest vispy.js

- codegen/createglapi.py
- vispy/gloo/gl/_es2.py
- vispy/gloo/gl/_gl2.py
- vispy/gloo/gl/_pyopengl2.py
See https://www.khronos.org/opengl/wiki/OpenGL_Type
> Fix OpenGL to ctypes type mapping

- examples/basics/gloo/hello_fbo.py
> Fix typo in examples/basics/gloo/hello_fbo.py 

- Makefile
- setup.py
- vispy/app/backends/__init__.py
- vispy/app/backends/_pyqt5.py
- vispy/app/backends/_pyside.py
- vispy/app/backends/_pyside2.py
- vispy/app/backends/_pyside6.py
- vispy/app/backends/_qt.py
- vispy/app/qt.py
- vispy/app/tests/test_backends.py
- vispy/util/config.py
- vispy/util/tests/test_import.py
- vispy/util/wrappers.py
As discussed in #1971, I've added the support for PySide6.
There is no major changes compared to PySide2. Please tell me if I missed something.
I've been able to run the various examples and use the PySide6 backend along a PySide2 installation. Is there anything more I need to do to test the changes ?
> Add PySide6 backend

- CONTRIBUTING.md
This is the one working for me.
> Fix URL to contributor guide

- examples/basics/scene/mesh_shading.py
- examples/basics/scene/mesh_texture.py
> Add headers and license to mesh filters examples

- vispy/visuals/filters/mesh.py
- vispy/visuals/mesh.py
- vispy/visuals/tests/test_mesh.py
> Fix changing mesh shading mode when initially None

- vispy/glsl/math/double.glsl
> Fix dead link in shader docstring

- vispy/glsl/math/double.glsl
> Fix typo in double shader

- vispy/visuals/axis.py
- vispy/visuals/tests/test_axis.py
Related to issue #2019
I've also removed some commented code, I don't know if I should have.
> Fix axis labeling issue when flipped

- examples/basics/scene/mesh_shading.py
- vispy/visuals/filters/mesh.py
Some fixes to the recent shading filter for correct/consistent behaviour.
> Fix various issues with shading in the MeshVisual

- vispy/visuals/volume.py
This PR upstreams the attenuated maximum intensity projection rendering mode from napari/napari#846 (by @sofroniewn) into vispy
> Add attenuated MIP (attenuated_mip) rendering mode to `VolumeVisual`

- vispy/gloo/gl/__init__.py
- vispy/gloo/gl/gl2.py
- vispy/gloo/glir.py
> Dont force selection of gl2 backend

- vispy/app/_detect_eventloop.py
- vispy/app/application.py
Fixes #1708
Do we need formal tests??
> Check for GUI eventloop when testing for jupyter kernel

- vispy/app/backends/_qt.py
- vispy/gloo/tests/test_glir.py
Fix #1889
Fixes it for me on Linux with wayland.
> Prevent translucent window with QOpenGLWidget

- .gitignore
- vispy/app/application.py
- vispy/app/backends/_pyqt4.py
- vispy/app/backends/_pyqt5.py
- vispy/app/backends/_pyside.py
- vispy/app/backends/_pyside2.py
- vispy/app/backends/_pyside6.py
- vispy/gloo/glir.py
- vispy/util/config.py
Closes #1790 ... from dec 2019 :)
> Set default log level to warning

- vispy/gloo/wrappers.py
- vispy/visuals/visual.py
- Clarify which attributes of the state are modified by each preset in the base `vispy.gloo.wrapper.set_state()` function.
- Add a link to `set_state()` in the higher-level `(Compound)Visual.(set|update)_gl_state()`.
> Document OpenGL state presets

- .github/workflows/main.yml
> Add apt update to CI environment

- examples/basics/visuals/image_transforms.py
- vispy/visuals/image.py
Addendum to #2085. I seem to have overlooked that second function.
> Also update clim for rgb

- examples/basics/scene/mesh_shading.py
- examples/basics/scene/mesh_texture.py
Following #2091
Addresses #2123
> Update light direction

- examples/basics/scene/mesh_shading.py
- examples/basics/scene/mesh_texture.py
> Make meshes upright and face the camera in mesh examples

- vispy/visuals/_scalable_textures.py
- vispy/visuals/tests/test_scalable_textures.py
> Fix auto clim calculation of all data is non-finite

- vispy/visuals/graphs/layouts/networkx_layout.py
> Dont warn about missing networkx until it's actually used

- vispy/visuals/_scalable_textures.py
- vispy/visuals/image.py
- vispy/visuals/tests/test_image.py
- vispy/visuals/tests/test_scalable_textures.py
Closes #2139 
I'm not super happy with the try/except in the ImageVisual, but also it seems like the most flexible and future-proof.
> Fix scalable textures clim_normalized when auto clims are used

- vispy/color/colormap.py
- vispy/visuals/colorbar.py
- vispy/visuals/image.py
- vispy/visuals/line/line.py
- vispy/visuals/mesh.py
- vispy/visuals/volume.py
Just some code sanitizing, as promised in https://github.com/vispy/vispy/pull/2150#discussion_r673866637.
> Refactor texture_lut() Colormap method to BaseColormap for cleaner usage

- examples/scene/volume_plane.py
> Fix volume_plane.py example not having a toggle for the animation

- vispy/visuals/infinite_line.py
This allows the InfiniteLine visual to have the line width changed.
> Add new parameters for InfiniteLineVisual: line width, antialias

- vispy/app/canvas.py
- vispy/gloo/glir.py
- vispy/util/wrappers.py
- vispy/visuals/image.py
- vispy/visuals/line/line.py
- vispy/visuals/text/text.py
- vispy/visuals/volume.py
> Cleanup some refs to webgl

- vispy/visuals/graphs/util.py
> Fix integer division when creating directed graphs

- vispy/visuals/line/arrow.py
> Clarified docstring for ArrowVisual

- doc/installation.rst
> Add optional dependencies section to installation instructions

- .github/workflows/wheels.yml
- README.rst
PR with no changes to see if CI can build (to check for #2285).
> Remove 32-bit linux wheel builds

- vispy/gloo/program.py
proposed update related to #2280
> Optimize shader regular expression compilation

- vispy/visuals/tests/test_text.py
- vispy/visuals/text/text.py
> Enable text depth testing

- vispy/util/transforms.py
A small typo fix in the docstring
> Typo fix in docstring

- vispy/app/backends/_pyglet.py
- vispy/app/backends/_wx.py
> Fix HIDPI on pyglet

- codegen/createglapi.py
- vispy/gloo/gl/_constants.py
As proposed by @djhoese 
closes #2386
> Fix character codec error on Windows Python <3.10

- .github/workflows/main.yml
- .github/workflows/wheels.yml
- .gitignore
- ci/requirements/linux_osmesa_deps_conda.txt
- ci/requirements/py39.yml
- setup.py
- vispy/app/backends/_qt.py
A continuation/addition to #2540 to debug osmesa CI issues.
> Update osmesa in CI

- .github/workflows/main.yml
- .github/workflows/wheels.yml
- .gitignore
- ci/requirements/py39.yml
- setup.py
- vispy/app/backends/_qt.py
> Change `devicePixelRatio` calls to `devicePixelRatioF` to get a floating point number instead of an integer

- vispy/plot/plotwidget.py
Hello, seems like there is a typo from copy/pasting the error message. I fixed it.
> Fix typo in plot widget error message

- README.rst
> Fix gallery link in README.rst

- setup.py
The backend is already there. Close #2591.
> Add extra for glfw

- vispy/visuals/volume.py
This limit is based on intuition rather than a rigorous analysis, but the limit is much looser than what was there before, and we now warn and clip rather than raising, which I think is more user-friendly.
See also #2587
> Clip step size based on maximum detail on an 8K monitor

- vispy/gloo/program.py
Small changes to error messages to add vairable names. I had to do this to debug some code, and I figured I might as well push it :P
> Add variable name in errors to help debugging

- doc/installation.rst
Corrects URL to managing python with Conda
> chore(docs): correct conda python URL

- examples/scene/instanced_mesh_picking.py
Hey everybody!
I was facing an issue described in #2615 and I came up with this example to solve it (borrowing from previous ones), which also demonstrates a bit how the get_transform() is used to translate from visual coordinate system to the canvas one. It just prints out the particular instance position clicked and some additional info
> Pick a specific instance of InstancedMesh

- vispy/color/colormap.py
- vispy/visuals/image.py
- vispy/visuals/surface_plot.py
Picking up the work from @JintaoLee-Roger in #2620.
Tidying up some glsl code to better align with the current implementation of other colormap-related code, and addressing failing tests.
> Allow setting bad color on colormap (continue #2620)

- .github/workflows/wheels.yml
In #2636 I have removed a few lines too much. 
This PR restore upload of sdist to pypi.
> Restore sdist upload to pypi 

- vispy/scene/widgets/widget.py
Simple change to make border width settable, like color and padding.
> add border width property and setter

- doc/governance/MAINTAINERS.md
My dad spotted a typo in my name in the maintainers list :P
> Fix name typo

- vispy/visuals/image.py
> Add missing update call to ImageVisual.set_data
